# Official Python Image
image: python:3.11.0-bullseye

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key: one-cache-for-everything
  paths:
    - Plone/eggs/
    - Plone/downloads/
    - ${PRE_COMMIT_HOME}
    - ${PIP_CACHE_DIR}

# Set execution order: first run jobs on 'test' stage on parallel
# then run jobs on 'report' stage
stages:
  - test
  - build
  - deploy

before_script:
  # Git for 3rd party source packages
  # - sudo apt-get update && sudo apt-get install -y --no-install-recommends git
  - git --version

  ## Install ssh-agent if not already installed, it is required by Docker.
  - "command -v ssh-agent >/dev/null || ( sudo apt-get update -y && sudo apt-get install openssh-client -y )"

  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ## Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
  ## following two lines.
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  # Check Python version
  - python -V
  - python3 -V
  - whereis python

build:
  tags:
    - shell
  stage: build
  script:
    # build docker
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin git.starzel.de:5050
    - docker build -t bfs/dokpool/py3 -f ./Docker/Dockerfile.review .
    - docker tag bfs/dokpool/py3:latest git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME
    - docker push git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME
  only:
    - review_py3

deploy_dev:
  tags:
    - shell
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    # Remove all unused images
    - docker system prune -a -f
    - docker pull git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME
    # Stop if it is running
    - docker stop dokpool-review-py3 || true
    - docker rm dokpool-review-py3 || true
    # Start instance and build demo data
    - docker run --detach --publish 8082:8082 --name dokpool-review-py3 git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME
    # Create the vanilla plone site
    - /usr/bin/wget -O- --user=admin --password=istrator --post-data='site_id=Plone&form.submitted=True&title=dokpool&default_language=de&portal_timezone=Europe/Berlin&extension_ids=plonetheme.barceloneta:default&extension_ids=plone.app.contenttypes:plone-content' http://127.0.0.1:8082/@@plone-addsite
    # Log in to the server.  This only needs to be done once.
    - /usr/bin/wget --save-cookies cookies.txt --keep-session-cookies --post-data '__ac_name=admin&__ac_password=istrator&form.submitted=True&buttons.login=Anmelden' --delete-after http://127.0.0.1:8082/Plone/login
    - /usr/bin/wget -O- --load-cookies cookies.txt --post-data='form.submitted=True&submit=True' http://127.0.0.1:8082/Plone/docpool_setup
  environment:
    name: dev
    url: https://review-two-bfs.starzel.de/
  only:
    - review_py3

undeploy_dev:
  tags:
    - shell
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app from dev.loc"
    - docker stop dokpool-review-py3 || true
    - docker rm dokpool-review-py3 || true
  when: manual
  environment:
    name: dev
    action: stop

lint_tests:
  tags:
    - docker
  stage: test
  script:
    # Install pipenv
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv --version
    # Buildout configuration
    - cd Plone
    # lint test
    - mkdir -p .venv
    - pipenv install
    - pipenv run pre-commit run -a

unit_tests:
  tags:
    - docker
  stage: test
  # still not available, see: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5004
  # success_with_warnings: True
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev python3-dev
    # Install pipenv
    - pip install pipenv
    - pipenv --version
    - cd Plone
    - cp config-template.cfg.tmpl config.cfg
    - echo -e "[buildout]\nlogin = admin\npassword = admin" > secret.cfg
    # build
    - mkdir -p .venv
    - pipenv install
    # Pin setuptools
    - pipenv install setuptools==65.5.1
    - pipenv run buildout -N -t 3 -c test_ci_server.cfg
    # Run tests
    - pipenv run ./bin/coverage erase
    - pipenv run ./bin/coverage run ./bin/test || exit 1
    ## Tests only docpool_setup (without robot)
    - pipenv run ./bin/coverage run ./bin/test -t test_demo_setup --all || exit 1
    ## Combines the previous two runs as parallel run is set
    - pipenv run ./bin/coverage combine
    - pipenv run ./bin/coverage html
    - pipenv run ./bin/coverage report
  cache:
    key: one-cache-for-everything
    paths:
      - Plone/.venv/
      - Plone/downloads/
      - Plone/eggs/
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths:
      - parts/test/htmlreport
