image: plone/server-builder:6.1.4

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  UV_CACHE_DIR: "$HOME/.cache/uv"
  PLONE_VERSION: "6.1.4"
  DOCKER_HOST: "unix:///runner/services/docker/docker.sock"

cache:
  paths:
    - ${PIP_CACHE_DIR}
    - ${UV_CACHE_DIR}

stages:
  - test
  - build
  - deploy

lint_tests:
  image: plone/server-builder:$PLONE_VERSION
  tags:
    - dind
  stage: test
  script:
    - cd backend
    - pip install --upgrade pip
    - pip install uv
    # Node.js installieren
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    - apt-get install -y nodejs
    - apt-get clean && rm -rf /var/lib/apt/lists/
    - npm install prettier
    # lint test
    - make lint
    - make format

unit_tests:
  image: plone/server-builder:$PLONE_VERSION
  tags:
    - dind
  stage: test
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev
    # build
    - cd backend
    - export VIRTUAL_ENV=$(pwd)
    - pip install --upgrade pip
    - pip install uv
    - make install
    - make coverage
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths:
      - parts/test/htmlreport

build_image:
  tags:
    - dind
  stage: build
  services:
    - docker:28.0.1-dind
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev curl docker.io
    # build docker
    # https://stackoverflow.com/questions/76654491/invalid-tag-missing-manifest-digest-when-exporting-nx-docker-image-to-gitlab-do
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - cd backend
    - export VIRTUAL_ENV=$(pwd)
    - pip install --upgrade pip
    - pip install uv
    - make build-image-ci
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$NIGHTLY_UPDATE == "True"'

deploy_review:
  image: curlimages/curl:8.18.0
  tags:
    - docker
  stage: deploy
  script:
    - curl --data-urlencode "" https://rundeck.portknox.info/api/16/job/18b65c46-4159-43ea-9989-7dc433fbccb0/run?authtoken=$authtoken
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$NIGHTLY_UPDATE == "True"'
