before_script:
  - cd Plone
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - /usr/bin/virtualenv .
  - cp config-template.cfg.tmpl config.cfg
  - ./bin/pip install -r requirements.txt
  - ./bin/buildout bootstrap
  - ./bin/buildout -N -t 3 -c test_ci_server.cfg
check:
  script:
    - pre-commit install
    - pre-commit run --all-files
test:
  script:
    - ./bin/test
