# Official Python Image
image: python:3.11.6-bullseye

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - ${PRE_COMMIT_HOME}
    - ${PIP_CACHE_DIR}

# Set execution order: first run jobs on 'test' stage on parallel
# then run jobs on 'report' stage
stages:
  - test
  - build
  - deploy

before_script:
  # Git for 3rd party source packages
  # - sudo apt-get update && sudo apt-get install -y --no-install-recommends git
  - git --version

  ## Install ssh-agent if not already installed, it is required by Docker.
  - "command -v ssh-agent >/dev/null || ( sudo apt-get update -y && sudo apt-get install openssh-client -y )"

  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ## Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
  ## following two lines.
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  # Check Python version
  - python -V
  - python3 -V
  - whereis python

build:
  tags:
    - shell
  stage: build
  script:
    # build docker
    # https://stackoverflow.com/questions/76654491/invalid-tag-missing-manifest-digest-when-exporting-nx-docker-image-to-gitlab-do
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin git.starzel.de:5050
    - cd backend
    - docker buildx build --push --provenance=false -t git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME .
  rules:
    - if: '$CI_COMMIT_BRANCH == "review_py3"'
    - if: '$NIGHTLY_UPDATE == "True"'

deploy_dev:
  tags:
    - shell
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    # Remove all unused images
    - docker system prune -a -f
    - docker pull git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME
    # Stop if it is running
    - docker stop dokpool-review-py3 || true
    - docker rm dokpool-review-py3 || true
    # Start instance and build demo data
    - docker run --detach --publish 8080:8080 -e GIT_COMMIT=$CI_COMMIT_SHORT_SHA -e GIT_REF_NAME=$CI_COMMIT_REF_NAME --name dokpool-review-py3 git.starzel.de:5050/bfs/dokpool/py3:$CI_COMMIT_REF_NAME
    # Create the vanilla plone site
    - /usr/bin/wget -O- --user=admin --password=admin --post-data='site_id=Plone&form.submitted=True&title=dokpool&default_language=de&portal_timezone=Europe/Berlin&extension_ids=plonetheme.barceloneta:default&extension_ids=plone.app.contenttypes:plone-content' http://127.0.0.1:8080/@@plone-addsite
    # Log in to the server.  This only needs to be done once.
    - /usr/bin/wget --save-cookies cookies.txt --keep-session-cookies --post-data '__ac_name=admin&__ac_password=admin&form.submitted=True&buttons.login=Anmelden' --delete-after http://127.0.0.1:8080/Plone/login
    - /usr/bin/wget -O- --load-cookies cookies.txt --post-data='form.submitted=True&submit=True' http://127.0.0.1:8080/Plone/docpool_setup
  environment:
    name: dev
    url: https://review-two-bfs.starzel.de/
  rules:
    - if: '$CI_COMMIT_BRANCH == "review_py3"'
    - if: '$NIGHTLY_UPDATE == "True"'

undeploy_dev:
  tags:
    - shell
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app from dev.loc"
    - docker stop dokpool-review-py3 || true
    - docker rm dokpool-review-py3 || true
  when: manual
  environment:
    name: dev
    action: stop

lint_tests:
  tags:
    - docker
  stage: test
  script:
    # Install pre-commit
    - pip install --upgrade pip
    - pip install pipx
    - pipx ensurepath
    - pipx install pre-commit==3.6.0
    # lint test
    - pipx run -- pre-commit run --a

unit_tests:
  tags:
    - docker
  stage: test
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev
    # build
    - make install
    - cd backend
    - make test_quiet
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths:
      - parts/test/htmlreport
