# Official Python Image
image: python:3.13.3-bullseye

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  UV_CACHE_DIR: "$HOME/.cache/uv"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - ${PIP_CACHE_DIR}
    - ${UV_CACHE_DIR}

# Set execution order: first run jobs on 'test' stage on parallel
# then run jobs on 'report' stage
stages:
  - test
  - build
  - deploy

lint_tests:
  image: plone/server-builder:6.1.1
  tags:
    - dind
  stage: test
  script:
    - cd backend
    - pip install --upgrade pip
    - pip install uv
    # lint test
    - make lint
    - make format

unit_tests:
  tags:
    - docker
  stage: test
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev
    # build
    - cd backend
    - export VIRTUAL_ENV=$(pwd)
    - pip install --upgrade pip
    - pip install uv
    - make install
    - make coverage
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
  artifacts:
    paths:
      - parts/test/htmlreport

build_image:
  tags:
    - shell
  stage: build
  script:
    # build docker
    # https://stackoverflow.com/questions/76654491/invalid-tag-missing-manifest-digest-when-exporting-nx-docker-image-to-gitlab-do
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin git.starzel.de:5050
    - cd backend
    # On the shell-runner we only have 3.7 and don't need anything newer for now.
    - sed -i'' -e 's/PYTHON_VERSION_MIN=3\.11/PYTHON_VERSION_MIN=3.7/g' Makefile
    - make build-image-ci
    - make build-image-varnish-ci
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$NIGHTLY_UPDATE == "True"'

deploy_review:
  tags:
    - shell
  stage: deploy
  script:
    - curl --data-urlencode "" https://rundeck.portknox.info/api/16/job/18b65c46-4159-43ea-9989-7dc433fbccb0/run?authtoken=$authtoken
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$NIGHTLY_UPDATE == "True"'
