before_script:
  - cd Plone
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - /usr/bin/virtualenv .
  - cp config-template.cfg.tmpl config.cfg
  - ./bin/pip install -r requirements.txt
  - ./bin/buildout bootstrap
  - ./bin/buildout -N -t 3 -c test_ci_server.cfg
#check:
#  script:
#    - pre-commit install
#    - pre-commit run --all-files
test:
  script:
    - ./bin/coverage erase
    - ./bin/coverage run ./bin/test || exit 1
# Tests only docpool_setup (without robot)
    - ./bin/coverage run ./bin/test -t test_demo_setup --all || exit 1
# Combines the previous two runs as parallel run is set
    - ./bin/coverage combine
    - ./bin/coverage html
    - ./bin/coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\%)/'
