image: plone/server-builder:6.1.4

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  UV_CACHE_DIR: "$HOME/.cache/uv"
  PLONE_VERSION: "6.1.4"
  # This variable is shared by both the DinD service and Docker client.
  # For the service, it will instruct DinD to create `docker.sock` here.
  # For the client, it tells the Docker client which Docker Unix socket to connect to.
  DOCKER_HOST: "unix:///runner/services/docker/docker.sock"

cache:
  paths:
    - ${PIP_CACHE_DIR}
    - ${UV_CACHE_DIR}

# Set execution order: first run jobs on 'test' stage on parallel
# then run jobs on 'report' stage
stages:
  - test
  - build
  - report
  - deploy

lint_tests:
  image: plone/server-builder:$PLONE_VERSION
  tags:
    - dind
  stage: test
  script:
    - cd backend
    - pip install --upgrade pip
    - pip install uv
    # Node.js installieren
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    - apt-get install -y nodejs
    - apt-get clean && rm -rf /var/lib/apt/lists/
    - npm install prettier
    # lint test
    - make lint
    - make format

unit_tests:
  image: plone/server-builder:$PLONE_VERSION
  tags:
    - dind
  stage: test
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev curl poppler-utils
    # build
    - cd backend

    - export VIRTUAL_ENV=$(pwd)
    - pip install --upgrade pip
    - pip install uv
    - make install
    - make coverage
  artifacts:
    paths:
      - backend/htmlcov/
      - backend/.coverage

acceptance_tests:
  image: git.starzel.de:5050/bfs/dokpool:acceptance
  tags:
    - dind
  stage: test
  script:
    - apt-get install -y poppler-utils
    - cd backend
    - pip install --upgrade pip
    - pip install uv
    - npm ci
    - make build-ui
    - make install-acceptance
    - make coverage-acceptance
  artifacts:
    when: always
    paths:
      - backend/screenshots/
      - backend/.coverage.acceptance

build_image:
  image: plone/server-builder:$PLONE_VERSION
  tags:
    - dind
  services:
    - docker:28.0.1-dind
  stage: build
  script:
    - apt update
    # LDAP client dependencies
    - apt-get install -y --no-install-recommends libsasl2-dev libldap2-dev libssl-dev curl poppler-utils docker.io
    # build
    - cd backend
    - export VIRTUAL_ENV=$(pwd)
    - pip install --upgrade pip
    - pip install uv
    # build docker
    # https://stackoverflow.com/questions/76654491/invalid-tag-missing-manifest-digest-when-exporting-nx-docker-image-to-gitlab-do
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - make build-image-ci
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "gui"'
    - if: '$NIGHTLY_UPDATE == "True"'

coverage_merge:
  stage: test
  image: python:3.12
  tags:
    - dind
  needs:
    - unit_tests
    - acceptance_tests
  script:
    - pip install coverage
    - mkdir cov
    - cp backend/.coverage* cov/ || true
    - cd cov
    - coverage combine
    - coverage xml
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - cov/coverage.xml

deploy_gui:
  image: curlimages/curl:8.18.0
  tags:
    - docker
  stage: deploy
  script:
    - curl --data-urlencode "" https://rundeck.portknox.info/api/16/job/ed75e90b-641c-43f2-b5a1-adcbf654a25f/run?authtoken=$authtoken
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "gui"'
    - if: '$NIGHTLY_UPDATE == "True"'
