before_script:
  - cd Plone
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - cp config-template.cfg.tmpl config.cfg
  - pip install -r requirements.txt
  - ./bin/buildout bootstrap
  - ./bin/buildout -N -t 3 -c config.cfg
check:
  script:
    - pre-commit install
    - pre-commit run --all-files
test:
  script:
    - ./bin/test

