repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1403]
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
        types: [file]
        files: \.(xml|zcml)$
      #   files: \.(xml|zcml|pt)$
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: /src/docpool.distribution/src/docpool/distribution/distributions/docpooldemo/content
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
        args: [--resolve-all-configs]

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-blind-except
  #         - flake8-debugger
  #         - flake8-deprecated
  #         - flake8-mutable
  #         # - flake8-plone-api
  #         - flake8-plone-hasattr
  #         - flake8-print
  #         - flake8-quotes
  #         - flake8-tidy-imports
  #         # - pep8-naming
  #       args: [--config=Plone/.flake8]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       additional_dependencies:
  #         - bandit[toml]
  #       args: [-c, Plone/pyproject.toml]
