---
version: "3.8"
name: dokpool

services:
  dokpool-zeoclient:
    image: git.starzel.de:5050/bfs/dokpool:python3
    deploy:
      mode: replicated
      replicas: 2
    environment:
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='dokpool-postgres' password='plone'"
      RELSTORAGE_CREATE_SCHEMA: "false"
    depends_on:
      dokpool-postgres:
        condition: service_started

  dokpool-postgres:
    image: postgres
    volumes:
      - dokpool-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    ports:
      - "5432:5432"

  dokpool-varnish:
    image: varnish
    volumes:
      - ./devops/varnish.vcl:/etc/varnish/default.vcl:ro

    environment:
      VARNISH_HTTP_PORT: 8080

    depends_on:
      dokpool-zeoclient:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  dokpool-db:
    external: false
