---
name: dokpool

services:
  zeoclient:
    image: git.starzel.de:5050/bfs/dokpool:python3
    deploy:
      mode: replicated
      replicas: 2
    environment:
      RELSTORAGE_DSN: "dbname='dokpool' user='dokpool' host='postgres' password='dokpool'"
      RELSTORAGE_CREATE_SCHEMA: "false"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres
    volumes:
      - dokpool-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dokpool
      POSTGRES_PASSWORD: dokpool
      POSTGRES_DB: dokpool
    ports:
      - "5432:5432"

  varnish:
    image: varnish
    volumes:
      - ./devops/varnish.vcl:/etc/varnish/default.vcl:ro

    environment:
      VARNISH_HTTP_PORT: 8080

    depends_on:
      zeoclient:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  dokpool-db:
    external: false
