---
name: dokpool

services:
  zeoclient:
    image: git.starzel.de:5050/bfs/dokpool:python3
    deploy:
      mode: replicated
      replicas: 2
    environment:
      RELSTORAGE_DSN: "dbname='dokpool' user='dokpool' host='postgres' password='dokpool'"
      RELSTORAGE_CREATE_SCHEMA: "false"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - net

  postgres:
    image: postgres
    volumes:
      - dokpool-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dokpool
      POSTGRES_PASSWORD: dokpool
      POSTGRES_DB: dokpool
    ports:
      - "5432:5432"
    networks:
      - net

  varnish:
    image: git.starzel.de:5050/bfs/dokpool:varnish
    build:
      context: ./devops/varnish-build/
      dockerfile: Dockerfile
      args:
        - VMOD_DEPS= "curl pkg-config nproc make gcc automake libtoolize libgetdns-dev"
    volumes:
      - ./devops/varnish.vcl:/etc/varnish/default.vcl:ro
    environment:
      VARNISH_HTTP_PORT: 8090
    depends_on:
      zeoclient:
        condition: service_healthy
    ports:
      - "8080:8090"
    networks:
      - net

  proxy:
    image: httpd
    volumes:
      - ./devops/custom_apacheconf/httpd_modified.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./devops/custom_apacheconf:/usr/local/apache2/conf/extra/:ro
    ports:
      - "9080:80"
    networks:
      - net

volumes:
  dokpool-db:
    external: false

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          ip_range: 172.25.0.0/24
          gateway: 172.25.0.1
