---
name: dokpool

services:
  zeoclient-init:
    image: registry.starzel.de/bfs/dokpool:python3
    command: "create-site"
    environment:
      RELSTORAGE_DSN: "dbname='dokpool' user='plone' host='postgres-init' password='plone'"
      RELSTORAGE_CREATE_SCHEMA: "true"
      DELETE_EXISTING: "1"
    depends_on:
      postgres-init:
        condition: service_started

  #  Onlyfor development & test
  # On production, we use the central patroni postgres
  postgres-init:
    image: postgres
    volumes:
      - dokpool-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    ports:
      - "5432:5432"

volumes:
  dokpool-db:
    external: false
