---
version: "3.8"
name: dokpool

services:
  dokpool-zeoclient1:
    profiles:
      - dokpool_review
    image: git.starzel.de:5050/bfs/dokpool:python3
    ports:
      - 8081:8081
    environment:
      LISTEN_PORT: 8081
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='dokpool-postgres' password='plone'"
      RELSTORAGE_CREATE_SCHEMA: false
    networks:
      - dokpool-backend

  dokpool-zeoclient2:
    profiles:
      - dokpool_review
    image: git.starzel.de:5050/bfs/dokpool:python3
    ports:
      - 8082:8082
    environment:
      LISTEN_PORT: 8082
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='dokpool-postgres' password='plone'"
      RELSTORAGE_CREATE_SCHEMA: false
    networks:
      - dokpool-backend

  dokpool-zeoclient-init:
    profiles:
      - dokpool_init
    image: git.starzel.de:5050/bfs/dokpool:python3
    ports:
      - 8082:8082
    environment:
      LISTEN_PORT: 8082
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='dokpool-postgres' password='plone'"
    networks:
      - dokpool-backend

  # Only for development & test
  # On production, we use the central patroni postgres
  dokpool-postgres:
    profiles:
      - dokpool_review
    image: postgres
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    ports:
      - "5432:5432"
    networks:
      - dokpool-backend

  dokpool-purger:
    profiles:
      - dokpool_review
    image: ghcr.io/kitconcept/cluster-purger:latest
    environment:
      PURGER_SERVICE_NAME: varnish
      PURGER_SERVICE_PORT: 80
      PURGER_MODE: "compose"
      PURGER_PUBLIC_SITES: "['plone.localhost']"

  dokpool-varnish:
    profiles:
      - dokpool_review
    image: varnish
    volumes:
      - ./devops/varnish.vcl:/etc/varnish/default.vcl:ro
    environment:
      - VARNISH_BACKEND_HOST=dokpool-zeoclient2
      - VARNISH_BACKEND_PORT=8081
    ports:
      - 80:80
    networks:
      - dokpool-backend
      - traefik_frontend

networks:
  traefik_frontend:
  dokpool-backend:
