[pytest]
#addopts = --browser chromium
# addopts = -v --browser chromium --headed
# The following config will enable the chromium browser and slow down the steps, so one can follow them.
# addopts = -v --browser chromium --headed --slowmo 900
