from zope.interface import implementer
from zope.schema.interfaces import IVocabularyFactory
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary


@implementer(IVocabularyFactory)
class Dom:
    def __call__(self, context=None):
        values = [
            "74 _deposition_ground_gamma surface activity_2 h",
            "75 _deposition_ground_gamma surface activity_1 d",
            "76 _deposition_ground_gamma surface activity_1 week",
            "77 _deposition_ground_gamma surface activity_1 month",
            "81 _deposition_ground_beta surface activity, long lived_1 d",
            "82 _deposition_ground_beta surface activity, after 24h_1 d",
            "84 _deposition_ground_beta surface activity_2 h",
            "85 _deposition_ground_beta surface activity_1 d",
            "86 _deposition_ground_beta surface activity_1 week",
            "87 _deposition_ground_beta surface activity_1 month",
            "94 _deposition_ground_alpha surface activity_2 h",
            "95 _deposition_ground_alpha surface activity_1 d",
            "96 _deposition_ground_alpha surface activity_1 week",
            "97 _deposition_ground_alpha surface activity_1 month",
            "100 ___gross dose rate_1 min",
            "101 ___gross dose rate_10 min",
            "102 ___gross dose rate_30 min",
            "103 ___gross dose rate_1 h",
            "104 ___gross dose rate_2 h",
            "105 ___gross dose rate_1 d",
            "107 ___gross dose rate_1 month",
            "109 ___gross dose rate_1 year",
            "110 ___high gross dose rate_",
            "111 ___high gross dose rate_10 min",
            "120 ___net dose rate_",
            "121 ___net dose rate_10 min",
            "123 ___net dose rate_1 h",
            "124 ___net dose rate_2 h",
            "125 ___net dose rate_1 d",
            "130 ___cosmic dose rate_",
            "131 ___cosmic dose rate_10 min",
            "134 ___cosmic dose rate_2 h",
            "135 ___cosmic dose rate_1 d",
            "140 ___terrestrial dose rate_",
            "141 ___terrestrial dose rate_10 min",
            "144 ___terrestrial dose rate_2 h",
            "145 ___terrestrial dose rate_1 d",
            "150 __ground_nuclide-spec. dose rate_",
            "152 __ground_nuclide-spec. dose rate_30 min",
            "153 __ground_nuclide-spec. dose rate_1 h",
            "154 __ground_nuclide-spec. dose rate_2 h",
            "155 ___dose rate_",
            "156 ___dose rate low energy _",
            "157 ___dose rate intermediate energy _",
            "160 _in situ_ground_gamma surface activity wet_",
            "161 _in situ_ground_gamma surface activity wet_10 min",
            "162 _in situ_ground_gamma surface activity wet_30 min",
            "163 _in situ_ground_gamma surface activity wet_1 h",
            "164 _in situ_ground_gamma surface activity wet_2 h",
            "167 _in situ_ground_gamma surface activity wet_1 month",
            "170 _in situ_ground_gamma surface activity_",
            "171 _in situ_ground_gamma surface activity_10 min",
            "172 _in situ_ground_gamma surface activity_30 min",
            "173 _in situ_ground_gamma surface activity_1 h",
            "174 _in situ_ground_gamma surface activity_2 h",
            "177 _in situ_ground_gamma surface activity_1 month",
            "180 _in situ_ground_gamma surface act. Net_",
            "181 _in situ_ground_gamma surface act. Net_10 min",
            "182 _in situ_ground_gamma surface act. Net_30 min",
            "183 _in situ_ground_gamma surface act. Net_1 h",
            "184 _in situ_ground_gamma surface act. Net_2 h",
            "187 _in situ_ground_gamma surface act. Net_1 month",
            "191 __ground_gamma surface activity_",
            "192 _calculated_ground_gamma surface activity_",
            "195 __ground_gamma surface activity concent._",
            "199 __ground__",
            "200 _air_aerosol particles_gamma activity concent._",
            "201 _air_aerosol particles_gamma activity concent._10 min",
            "202 _air_aerosol particles_gamma activity concent._30 min",
            "203 _air_aerosol particles_gamma activity concent._1 h",
            "204 _air_aerosol particles_gamma activity concent._2 h",
            "205 _air_aerosol particles_gamma activity concent._1 d",
            "206 _air_aerosol particles_gamma activity concent._1 week",
            "207 _air_aerosol particles_gamma activity concent._1 month",
            "210 _air_aerosol particles_gamma activity concent._2 weeks",
            "211 _air_aerosol particles_total gamma act. concent._10 min",
            "212 _air_aerosol particles_total gamma act. concent._30 min",
            "213 _air_aerosol particles_total gamma act. concent._1 h",
            "214 _air_aerosol particles_total gamma act. Concent._2 h",
            "220 _air_aerosol particles_artificial beta activity concent._",
            "221 _air_aerosol particles_artificial beta activity concent._10 min",
            "221 _air_aerosol particles_artificial beta activity concent._10 min"
            "222 _air_aerosol particles_artificial beta activity concent._30 min",
            "222 _air_aerosol particles_artificial beta activity concent._30 min"
            "223 _air_aerosol particles_artificial beta activity concent._1 h",
            "224 _air_aerosol particles_artificial beta activity concent._2 h",
            "225 _air_aerosol particles_artificial beta activity concent._1 d",
            "230 _air_aerosol particles_beta activity concent._",
            "231 _air_aerosol particles_beta activity concent._10 min",
            "232 _air_aerosol particles_beta activity concent._30 min",
            "233 _air_aerosol particles_beta activity concent._1 h",
            "234 _air_aerosol particles_beta activity concent._2 h",
            "235 _air_aerosol particles_beta activity concent._1 d",
            "237 _air_aerosol particles_beta activity concent._1 month",
            "241 _air_aerosol particles_total beta act.concent._10 min",
            "242 _air_aerosol particles_total beta act.concent._30 min",
            "243 _air_aerosol particles_total beta act.concent._1 h",
            "244 _air_aerosol particles_total beta act.concent._2 h",
            "245 _air_aerosol particles_total beta act.concent._1 d",
            "252 _air_aerosol particles_artificial alpha activity concent._30 min",
            "252 _air_aerosol particles_artificial alpha activity concent._30 min"
            "253 _air_aerosol particles_artificial alpha activity concent._1 h",
            "254 _air_aerosol particles_artificial alpha activity concent._2 h",
            "255 _air_aerosol particles_artificial alpha activity concent._1 d",
            "262 _air_aerosol particles_alpha activity concent._30 min",
            "264 _air_aerosol particles_alpha activity concent._2 h",
            "265 _air_aerosol particles_alpha activity concent._1 d",
            "267 _air_aerosol particles_alpha activity concent._1 month",
            "272 _air_aerosol particles_total alpha act.concent._30 min",
            "274 _air_aerosol particles_total alpha act.concent._2 h",
            "275 _air_aerosol particles_total alpha act.concent._1 d",
            "281 _air_aerosol particles_beta activity concent., long lived_10 min",
            "281 _air_aerosol particles_beta activity concent., long lived_10 min"
            "282 _air_aerosol particles_beta activity concent., long lived_30 min",
            "282 _air_aerosol particles_beta activity concent., long lived_30 min"
            "283 _air_aerosol particles_beta activity concent., long lived_1 h",
            "284 _air_aerosol particles_beta activity concent., long lived_2 h",
            "285 _air_aerosol particles_beta activity concent., long lived_1 d",
            "287 _air_aerosol particles_beta activity concent., long lived_1 month",
            "287 _air_aerosol particles_beta activity concent., long lived_1 month"
            "289 _air_aerosol particles_beta activity concent., 10h later_2h",
            "291 _air_aerosol particles_total emission_10 min",
            "292 _air_aerosol particles_total emission_30 min",
            "300 _air_iodine_activity concentration_",
            "301 _air_iodine_activity concentration_10 min",
            "302 _air_iodine_activity concentration_30 min",
            "304 _air_iodine_activity concentration_2 h",
            "305 _air_iodine_activity concentration_1 d",
            "306 _air_iodine_activity concentration_1 week",
            "307 _air_iodine_activity concentration_2 weeks",
            "309 _air_iodine_activity concentration_4 h",
            "311 _air_iodine_total emission_10 min",
            "312 _air_iodine_total emission_30 min",
            "320 _air_noble gases_activity concentration_",
            "321 _air_noble gases_activity concentration_10 min",
            "322 _air_noble gases_activity concentration_30 min",
            "324 _air_noble gases_activity concentration_2 h",
            "325 _air_noble gases_activity concentration_1 d",
            "327 _air_noble gases_activity concentration_1 month",
            "331 _air_noble gases_high activity concent._10 min",
            "332 _air_noble gases_high activity concent._30 min",
            "341 _air_noble gases_total emission_10 min",
            "342 _air_noble gases_total emission_30 min",
            "353 _air_aerosol particles_gamma activity_1 h",
            "355 _air_aerosol particles_gamma activity_1 d",
            "356 _air_aerosol particles_gamma activity_1 week",
            "357 _air_aerosol particles_gamma activity_1 month",
            "358 _air_aerosol particles_gamma activity_3 months",
            "359 _air_aerosol particles_gamma activity_1 year",
            "363 _air_aerosol particles_beta activity_1 h",
            "365 _air_aerosol particles_beta activity_1 d",
            "366 _air_aerosol particles_beta activity_1 week",
            "367 _air_aerosol particles_beta activity_1 month",
            "368 _air_aerosol particles_beta activity_3 months",
            "369 _air_aerosol particles_beta activity_1 year",
            "373 _air_aerosol particles_total beta activity_1 h",
            "375 _air_aerosol particles_total beta activity_1 d",
            "376 _air_aerosol particles_total beta activity_1 week",
            "377 _air_aerosol particles_total beta activity_1 month",
            "378 _air_aerosol particles_total beta activity_3 months",
            "379 _air_aerosol particles_total beta activity_1 year",
            "383 _air_aerosol particles_alpha activity_1 h",
            "385 _air_aerosol particles_alpha activity_1 d",
            "386 _air_aerosol particles_alpha activity_1 week",
            "387 _air_aerosol particles_alpha activity_1 month",
            "388 _air_aerosol particles_alpha activity_3 months",
            "389 _air_aerosol particles_alpha activity_1 year",
            "393 _air_aerosol particles_total alpha activity_1 h",
            "395 _air_aerosol particles_total alpha activity_1 d",
            "396 _air_aerosol particles_total alpha activity_1 week",
            "397 _air_aerosol particles_total alpha activity_1 month",
            "398 _air_aerosol particles_total alpha activity_3 months",
            "399 _air_aerosol particles_total alpha activity_1 year",
            "403 _air_iodine_activity_1 h",
            "405 _air_iodine_activity_1 d",
            "406 _air_iodine_activity_1 week",
            "407 _air_iodine_activity_1 month",
            "408 _air_iodine_activity_3 months",
            "409 _air_iodine_activity_1 year",
            "411 _air_aerosol particles_alpha activity conc., long lived_10 min",
            "411 _air_aerosol particles_alpha activity conc., long lived_10 min"
            "412 _air_aerosol particles_alpha activity conc., long lived_30 min",
            "412 _air_aerosol particles_alpha activity conc., long lived_30 min"
            "413 _air_aerosol particles_alpha activity conc., long lived_1 h",
            "414 _air_aerosol particles_alpha activity conc., long lived_2 h",
            "415 _air_aerosol particles_alpha activity conc., long lived_1 d",
            "417 _air_aerosol particles_alpha activity conc., long lived_1 month",
            "417 _air_aerosol particles_alpha activity conc., long lived_1 month"
            "423 _air_noble gases_gamma activity_1 h",
            "425 _air_noble gases_gamma activity_1 d",
            "426 _air_noble gases_gamma activity_1 week",
            "427 _air_noble gases_gamma activity_1 month",
            "428 _air_noble gases_gamma activity_3 months",
            "429 _air_noble gases_gamma activity_1 year",
            "433 _air_noble gases_total gamma activity_1 h",
            "435 _air_noble gases_total gamma activity_1 d",
            "436 _air_noble gases_total gamma activity_1 week",
            "437 _air_noble gases_total gamma activity_1 month",
            "438 _air_noble gases_total gamma activity_3 months",
            "439 _air_noble gases_total gamma activity_1 year",
            "443 _air_noble gases_beta activity_1 h",
            "445 _air_noble gases_beta activity_1 d",
            "446 _air_noble gases_beta activity_1 week",
            "447 _air_noble gases_beta activity_1 month",
            "448 _air_noble gases_beta activity_3 months",
            "449 _air_noble gases_beta activity_1 year",
            "453 _air_noble gases_total beta activity_1 h",
            "455 _air_noble gases_total beta activity_1 d",
            "456 _air_noble gases_total beta activity_1 week",
            "457 _air_noble gases_total beta activity_1 month",
            "458 _air_noble gases_total beta activity_3 months",
            "459 _air_noble gases_total beta activity_1 year",
            "563 _air_gases_beta activity_1 h",
            "565 _air_gases_beta activity_1 d",
            "566 _air_gases_beta activity_1 week",
            "567 _air_gases_beta activity_1 month",
            "568 _air_gases_beta activity_3 months",
            "569 _air_gases_beta activity_1 year",
            "573 _air_aerosol particles_beta activity,  long lived_1 h",
            "575 _air_aerosol particles_beta activity,  long lived_1 d",
            "576 _air_aerosol particles_beta activity,  long lived_1 week",
            "577 _air_aerosol particles_beta activity,  long lived_1 month",
            "578 _air_aerosol particles_beta activity,  long lived_3 months",
            "579 _air_aerosol particles_beta activity,  long lived_1 year",
            "583 _air__volume_1 h",
            "585 _air__volume_1 d",
            "586 _air__volume_1 week",
            "587 _air__volume_1 month",
            "588 _air__volume_3 months",
            "589 _air__volume_1 year",
            " ____",
            "591 _air__volume stream_10 min",
            "592 _air__volume stream_30 min",
            "593 _air_stack_temperature_10 min",
            "594 _air_stack_temperature_30 min",
            "595 _air_stack_temperature_1 h",
            "596 _air__temperature_10 min",
            "597 _air__temperature_30 min",
            "598 _air__temperature_1 h",
            "599 _air__overall loss factor _",
            "606 _water__gamma activity_1 week",
            "607 _water__gamma activity_1 month",
            "608 _water__gamma activity_3 months",
            "609 _water__gamma activity_1 year",
            "623 _water__beta activity_1 h",
            "625 _water__beta activity_1 d",
            "626 _water__beta activity_1 week",
            "627 _water__beta activity_1 month",
            "628 _water__beta activity_3 months",
            "629 _water__beta activity_1 year",
            "646 _water__alpha activity_1 week",
            "647 _water__alpha activity_1 month",
            "648 _water__alpha activity_3 months",
            "649 _water__alpha activity_1 year",
            "656 _water__total alpha activity_1 week",
            "657 _water__total alpha activity_1 month",
            "658 _water__total alpha activity_3 months",
            "659 _water__total alpha activity_1 year",
            "661 _water__gamma act.conc._10 min",
            "662 _water__gamma act.conc._30 min",
            "663 _water__gamma act.conc._1 h",
            "664 _water__gamma act.conc._2 h",
            "665 _water__gamma act.conc._1 d",
            "671 _water__specific act.conc._10 min",
            "672 _water__specific act.conc._30 min",
            "673 _water__specific act.conc._1 h",
            "674 _water__specific act.conc._2 h",
            "691 _air__counting rate_10 min",
            "693 _air__counting rate_1 h",
            "695 _air__counting rate_1 d",
            "696 _air__counting rate_1 week",
            "697 _air__counting rate_1 month",
            "698 _air__counting rate_3 months",
            "706 _water__volume_1 week",
            "707 _water__volume_1 month",
            "708 _water__volume_3 months",
            "709 _water__volume_1 year",
            "711 _water__volume stream_10 min",
            "712 _water__volume stream_30 min",
            "716 _water__temperature_10 min",
            "717 _water__temperature_30 min",
            "786 _air_meteo_temperature_10 min",
            "787 _air_meteo_temperature_30 min",
            "788 _air_meteo_temperature_1 h",
            "791 __meteo_air pressure_10 min",
            "793 __meteo_air pressure_1 h",
            "796 __meteo_rel. humidity_10 min",
            "797 __meteo_rel. humidity_1 h",
            "800 __meteo_precipitation_",
            "801 __meteo_precipitation_10 min",
            "802 __meteo_precipitation_30 min",
            "803 __meteo_precipitation_1 h",
            "804 __meteo_precipitation_2 h",
            "805 __meteo_precipitation_1 d",
            "806 __meteo_precipitation_1 wo",
            "807 __meteo_precipitation_1 m",
            "815 __meteo_precipitation snow_1 d",
            "818 __meteo_precipitation probability_15 min",
            "819 __meteo_precipitation probability_2 h",
            "824 __meteo_precipitation intensity_",
            "825 __meteo_precipitation intensity_",
            "827 __meteo_precipitation relativly_10 min",
            "831 __meteo_wind velocity_10 min",
            "832 __meteo_wind velocity_30 min",
            "833 __meteo_wind velocity_1 h",
            "834 __meteo_wind velocity_2 h",
            "836 __meteo_wind veloc. fluctuation (sigma w)_10 min",
            "837 __meteo_wind veloc. fluctuation (sigma w)_30 min",
            "838 __meteo_wind veloc. fluctuation (sigma w)_1 h",
            "841 __meteo_wind direction_10 min",
            "842 __meteo_wind direction_30 min",
            "843 __meteo_wind direction_1 h",
            "844 __meteo_wind direction_2 h",
            "851 __meteo_wind dir. fluctuation (sigma ?)_10 min",
            "852 __meteo_wind dir. fluctuation (sigma ?)_30 min",
            "853 __meteo_wind dir. fluctuation (sigma ?)_1 h",
            "856 __meteo_wind dir. fluctuation (sigma ?)_10 min",
            "857 __meteo_wind dir. fluctuation (sigma ?)_30 min",
            "858 __meteo_wind dir. fluctuation (sigma ?)_1 h",
            "861 __meteo_radiation balance_10 min",
            "862 __meteo_radiation balance_30 min",
            "863 __meteo_radiation balance_1 h",
            "876 __meteo_stability class (1-6) (sigma w)_10 min",
            "877 __meteo_stability class (1-6) (sigma w)_30 min",
            "878 __meteo_stability class (1-6) (sigma w)_1 h",
            "881 __meteo_stability class (1-6) (radiation balance)_10 min",
            "882 __meteo_stability class (1-6) (radiation balance)_30 min",
            "883 __meteo_stability class (1-6) (radiation balance)_1 h",
            "886 __meteo_stability class (1-6) (sigma ?)_10 min",
            "887 __meteo_stability class (1-6) (sigma ?)_30 min",
            "888 __meteo_stability class (1-6) (sigma ?)_1 h",
            "891 __meteo_stability class (1-6) (sigma ?)_10 min",
            "892 __meteo_stability class (1-6) (sigma ?)_30 min",
            "893 __meteo_stability class (1-6) (sigma ?)_1 h",
            "896 __meteo_stability class (1-6) (temp. gradient)_10 min",
            "897 __meteo_stability class (1-6) (temp. gradient)_30 min",
            "898 __meteo_stability class (1-6) (temp. gradient)_1 h",
            "951 ___electrical power_10 min",
            "953 ___electrical power_1 h",
            "955 ___electrical power_1 d",
            "956 ___electrical power_1 week",
            "957 ___electrical power_1 month",
            "958 ___electrical power_3 months",
            "959 ___electrical power_1 year",
            "961 ___therm. power_10 min",
            "963 ___therm. power_1 h",
            "965 ___therm. power_1 d",
            "966 ___therm. power_1 week",
            "967 ___therm. power_1 month",
            "968 ___therm. power_3 months",
            "969 ___therm. power_1 year",
        ]
        return SimpleVocabulary([SimpleTerm(value=value, token=value, title=value) for value in values])


DomFactory = Dom()
