(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["docpool"],{

/***/ "./.plone/++theme++docpool.theme/static/docpool.js":
/*!*********************************************************!*\
  !*** ./.plone/++theme++docpool.theme/static/docpool.js ***!
  \*********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("﻿Promise.all(/*! AMD require */[__webpack_require__.e(\"jquery-marquee\"), __webpack_require__.e(10)]).then(function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = [__webpack_require__(/*! jquery */ \"./.plone/++plone++static/components/jquery/dist/jquery.min.js\"),\r\n         __webpack_require__(/*! intercom */ \"./.plone/++theme++docpool.theme/static/intercom.min.js\"),\r\n         __webpack_require__(/*! notify */ \"./.plone/++theme++docpool.theme/static/notify.min.js\"),\r\n         __webpack_require__(/*! jquery-marquee */ \"./.plone/++theme++docpool.theme/static/jquery.marquee.js\"),\r\n         __webpack_require__(/*! docpool-functions */ \"./.plone/++theme++docpool.theme/static/functions.js\"),\r\n         ]; (function($) {\r\n\t'use strict';\r\n\r\n\tfunction loadDyn () {\r\n\t\t$(\"#mesz\").load (\"refresh_time #time_table\");\r\n\t\t$(\"section.portletRecent\").load (\"refresh_recent #recent_content\");\r\n\t}\r\n\r\n    function getURLParam(name){\r\n       var regex = '[?&]'+name+'=([^&]*)';\r\n       var query = location.search;\r\n       if(name=(new RegExp(regex)).exec(query))\r\n          return name[1];\r\n    }\r\n\r\n\tvar myDynTimer = setInterval ( loadDyn, 60000 );\r\n\t$('.documentByLine a').removeAttr('href').addClass('commentator');\r\n\tvar type = $('#form-widgets-docType')\r\n\tif ((type[0] != null) && (type[0].selectedIndex != null)) {\r\n\t    var dtParam = getURLParam('form.widgets.docType:list')\r\n\t    if (typeof dtParam != 'undefined') {\r\n    \t    type.val(dtParam);\r\n\t    }\r\n\t\tvar option = type[0].options[type[0].selectedIndex];\r\n\t\tvar value = option.text;\r\n\t\tvar title = $('h1.documentFirstHeading').text();\r\n\t\t$('h1.documentFirstHeading').text(title + ' (' + value + ')'); \r\n\t}\r\n\r\n    $(document).ready ( function () {\r\n        $('.marquee').marquee({\r\n                pauseOnHover:true,\r\n                duration: 10000,\r\n                //gap in pixels between the tickers\r\n                gap: 50,\r\n            }\r\n        );\r\n    });\r\n\r\n}).apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__);}).catch(__webpack_require__.oe);\r\n\r\n$(document).on(\"click\", '.collapsible', function(event) {\r\n    this.classList.toggle(\"active\");\r\n    var content = this.nextElementSibling;\r\n    if (content.style.maxHeight){\r\n        content.style.maxHeight = null;\r\n    } else {\r\n        content.style.maxHeight = content.scrollHeight + \"px\";\r\n    }\r\n});\r\n\n\n//# sourceURL=webpack:///./.plone/++theme++docpool.theme/static/docpool.js?");

/***/ })

}]);