# -*- coding: utf-8 -*-
from plone.app.vocabularies.terms import safe_simplevocabulary_from_values
from zope.interface import implementer
from zope.schema.interfaces import IVocabularyFactory


@implementer(IVocabularyFactory)
class Dom(object):

    def __call__(self, context=None):
        values = [
            u'74 _deposition_ground_gamma surface activity_2 h',
            u'75 _deposition_ground_gamma surface activity_1 d',
            u'76 _deposition_ground_gamma surface activity_1 week',
            u'77 _deposition_ground_gamma surface activity_1 month',
            u'81 _deposition_ground_beta surface activity, long lived_1 d',
            u'82 _deposition_ground_beta surface activity, after 24h_1 d',
            u'84 _deposition_ground_beta surface activity_2 h',
            u'85 _deposition_ground_beta surface activity_1 d',
            u'86 _deposition_ground_beta surface activity_1 week',
            u'87 _deposition_ground_beta surface activity_1 month',
            u'94 _deposition_ground_alpha surface activity_2 h',
            u'95 _deposition_ground_alpha surface activity_1 d',
            u'96 _deposition_ground_alpha surface activity_1 week',
            u'97 _deposition_ground_alpha surface activity_1 month',
            u'100 ___gross dose rate_1 min',
            u'101 ___gross dose rate_10 min',
            u'102 ___gross dose rate_30 min',
            u'103 ___gross dose rate_1 h',
            u'104 ___gross dose rate_2 h',
            u'105 ___gross dose rate_1 d',
            u'107 ___gross dose rate_1 month',
            u'109 ___gross dose rate_1 year',
            u'110 ___high gross dose rate_',
            u'111 ___high gross dose rate_10 min',
            u'120 ___net dose rate_',
            u'121 ___net dose rate_10 min',
            u'123 ___net dose rate_1 h',
            u'124 ___net dose rate_2 h',
            u'125 ___net dose rate_1 d',
            u'130 ___cosmic dose rate_',
            u'131 ___cosmic dose rate_10 min',
            u'134 ___cosmic dose rate_2 h',
            u'135 ___cosmic dose rate_1 d',
            u'140 ___terrestrial dose rate_',
            u'141 ___terrestrial dose rate_10 min',
            u'144 ___terrestrial dose rate_2 h',
            u'145 ___terrestrial dose rate_1 d',
            u'150 __ground_nuclide-spec. dose rate_',
            u'152 __ground_nuclide-spec. dose rate_30 min',
            u'153 __ground_nuclide-spec. dose rate_1 h',
            u'154 __ground_nuclide-spec. dose rate_2 h',
            u'155 ___dose rate_',
            u'156 ___dose rate low energy _',
            u'157 ___dose rate intermediate energy _',
            u'160 _in situ_ground_gamma surface activity wet_',
            u'161 _in situ_ground_gamma surface activity wet_10 min',
            u'162 _in situ_ground_gamma surface activity wet_30 min',
            u'163 _in situ_ground_gamma surface activity wet_1 h',
            u'164 _in situ_ground_gamma surface activity wet_2 h',
            u'167 _in situ_ground_gamma surface activity wet_1 month',
            u'170 _in situ_ground_gamma surface activity_',
            u'171 _in situ_ground_gamma surface activity_10 min',
            u'172 _in situ_ground_gamma surface activity_30 min',
            u'173 _in situ_ground_gamma surface activity_1 h',
            u'174 _in situ_ground_gamma surface activity_2 h',
            u'177 _in situ_ground_gamma surface activity_1 month',
            u'180 _in situ_ground_gamma surface act. Net_',
            u'181 _in situ_ground_gamma surface act. Net_10 min',
            u'182 _in situ_ground_gamma surface act. Net_30 min',
            u'183 _in situ_ground_gamma surface act. Net_1 h',
            u'184 _in situ_ground_gamma surface act. Net_2 h',
            u'187 _in situ_ground_gamma surface act. Net_1 month',
            u'191 __ground_gamma surface activity_',
            u'192 _calculated_ground_gamma surface activity_',
            u'195 __ground_gamma surface activity concent._',
            u'199 __ground__',
            u'200 _air_aerosol particles_gamma activity concent._',
            u'201 _air_aerosol particles_gamma activity concent._10 min',
            u'202 _air_aerosol particles_gamma activity concent._30 min',
            u'203 _air_aerosol particles_gamma activity concent._1 h',
            u'204 _air_aerosol particles_gamma activity concent._2 h',
            u'205 _air_aerosol particles_gamma activity concent._1 d',
            u'206 _air_aerosol particles_gamma activity concent._1 week',
            u'207 _air_aerosol particles_gamma activity concent._1 month',
            u'210 _air_aerosol particles_gamma activity concent._2 weeks',
            u'211 _air_aerosol particles_total gamma act. concent._10 min',
            u'212 _air_aerosol particles_total gamma act. concent._30 min',
            u'213 _air_aerosol particles_total gamma act. concent._1 h',
            u'214 _air_aerosol particles_total gamma act. Concent._2 h',
            u'220 _air_aerosol particles_artificial beta activity concent._',
            u'221 _air_aerosol particles_artificial beta activity concent._10 min',
            u'221 _air_aerosol particles_artificial beta activity concent._10 min'
            u'222 _air_aerosol particles_artificial beta activity concent._30 min',
            u'222 _air_aerosol particles_artificial beta activity concent._30 min'
            u'223 _air_aerosol particles_artificial beta activity concent._1 h',
            u'224 _air_aerosol particles_artificial beta activity concent._2 h',
            u'225 _air_aerosol particles_artificial beta activity concent._1 d',
            u'230 _air_aerosol particles_beta activity concent._',
            u'231 _air_aerosol particles_beta activity concent._10 min',
            u'232 _air_aerosol particles_beta activity concent._30 min',
            u'233 _air_aerosol particles_beta activity concent._1 h',
            u'234 _air_aerosol particles_beta activity concent._2 h',
            u'235 _air_aerosol particles_beta activity concent._1 d',
            u'237 _air_aerosol particles_beta activity concent._1 month',
            u'241 _air_aerosol particles_total beta act.concent._10 min',
            u'242 _air_aerosol particles_total beta act.concent._30 min',
            u'243 _air_aerosol particles_total beta act.concent._1 h',
            u'244 _air_aerosol particles_total beta act.concent._2 h',
            u'245 _air_aerosol particles_total beta act.concent._1 d',
            u'252 _air_aerosol particles_artificial alpha activity concent._30 min',
            u'252 _air_aerosol particles_artificial alpha activity concent._30 min'
            u'253 _air_aerosol particles_artificial alpha activity concent._1 h',
            u'254 _air_aerosol particles_artificial alpha activity concent._2 h',
            u'255 _air_aerosol particles_artificial alpha activity concent._1 d',
            u'262 _air_aerosol particles_alpha activity concent._30 min',
            u'264 _air_aerosol particles_alpha activity concent._2 h',
            u'265 _air_aerosol particles_alpha activity concent._1 d',
            u'267 _air_aerosol particles_alpha activity concent._1 month',
            u'272 _air_aerosol particles_total alpha act.concent._30 min',
            u'274 _air_aerosol particles_total alpha act.concent._2 h',
            u'275 _air_aerosol particles_total alpha act.concent._1 d',
            u'281 _air_aerosol particles_beta activity concent., long lived_10 min',
            u'281 _air_aerosol particles_beta activity concent., long lived_10 min'
            u'282 _air_aerosol particles_beta activity concent., long lived_30 min',
            u'282 _air_aerosol particles_beta activity concent., long lived_30 min'
            u'283 _air_aerosol particles_beta activity concent., long lived_1 h',
            u'284 _air_aerosol particles_beta activity concent., long lived_2 h',
            u'285 _air_aerosol particles_beta activity concent., long lived_1 d',
            u'287 _air_aerosol particles_beta activity concent., long lived_1 month',
            u'287 _air_aerosol particles_beta activity concent., long lived_1 month'
            u'289 _air_aerosol particles_beta activity concent., 10h later_2h',
            u'291 _air_aerosol particles_total emission_10 min',
            u'292 _air_aerosol particles_total emission_30 min',
            u'300 _air_iodine_activity concentration_',
            u'301 _air_iodine_activity concentration_10 min',
            u'302 _air_iodine_activity concentration_30 min',
            u'304 _air_iodine_activity concentration_2 h',
            u'305 _air_iodine_activity concentration_1 d',
            u'306 _air_iodine_activity concentration_1 week',
            u'307 _air_iodine_activity concentration_2 weeks',
            u'309 _air_iodine_activity concentration_4 h',
            u'311 _air_iodine_total emission_10 min',
            u'312 _air_iodine_total emission_30 min',
            u'320 _air_noble gases_activity concentration_',
            u'321 _air_noble gases_activity concentration_10 min',
            u'322 _air_noble gases_activity concentration_30 min',
            u'324 _air_noble gases_activity concentration_2 h',
            u'325 _air_noble gases_activity concentration_1 d',
            u'327 _air_noble gases_activity concentration_1 month',
            u'331 _air_noble gases_high activity concent._10 min',
            u'332 _air_noble gases_high activity concent._30 min',
            u'341 _air_noble gases_total emission_10 min',
            u'342 _air_noble gases_total emission_30 min',
            u'353 _air_aerosol particles_gamma activity_1 h',
            u'355 _air_aerosol particles_gamma activity_1 d',
            u'356 _air_aerosol particles_gamma activity_1 week',
            u'357 _air_aerosol particles_gamma activity_1 month',
            u'358 _air_aerosol particles_gamma activity_3 months',
            u'359 _air_aerosol particles_gamma activity_1 year',
            u'363 _air_aerosol particles_beta activity_1 h',
            u'365 _air_aerosol particles_beta activity_1 d',
            u'366 _air_aerosol particles_beta activity_1 week',
            u'367 _air_aerosol particles_beta activity_1 month',
            u'368 _air_aerosol particles_beta activity_3 months',
            u'369 _air_aerosol particles_beta activity_1 year',
            u'373 _air_aerosol particles_total beta activity_1 h',
            u'375 _air_aerosol particles_total beta activity_1 d',
            u'376 _air_aerosol particles_total beta activity_1 week',
            u'377 _air_aerosol particles_total beta activity_1 month',
            u'378 _air_aerosol particles_total beta activity_3 months',
            u'379 _air_aerosol particles_total beta activity_1 year',
            u'383 _air_aerosol particles_alpha activity_1 h',
            u'385 _air_aerosol particles_alpha activity_1 d',
            u'386 _air_aerosol particles_alpha activity_1 week',
            u'387 _air_aerosol particles_alpha activity_1 month',
            u'388 _air_aerosol particles_alpha activity_3 months',
            u'389 _air_aerosol particles_alpha activity_1 year',
            u'393 _air_aerosol particles_total alpha activity_1 h',
            u'395 _air_aerosol particles_total alpha activity_1 d',
            u'396 _air_aerosol particles_total alpha activity_1 week',
            u'397 _air_aerosol particles_total alpha activity_1 month',
            u'398 _air_aerosol particles_total alpha activity_3 months',
            u'399 _air_aerosol particles_total alpha activity_1 year',
            u'403 _air_iodine_activity_1 h',
            u'405 _air_iodine_activity_1 d',
            u'406 _air_iodine_activity_1 week',
            u'407 _air_iodine_activity_1 month',
            u'408 _air_iodine_activity_3 months',
            u'409 _air_iodine_activity_1 year',
            u'411 _air_aerosol particles_alpha activity conc., long lived_10 min',
            u'411 _air_aerosol particles_alpha activity conc., long lived_10 min'
            u'412 _air_aerosol particles_alpha activity conc., long lived_30 min',
            u'412 _air_aerosol particles_alpha activity conc., long lived_30 min'
            u'413 _air_aerosol particles_alpha activity conc., long lived_1 h',
            u'414 _air_aerosol particles_alpha activity conc., long lived_2 h',
            u'415 _air_aerosol particles_alpha activity conc., long lived_1 d',
            u'417 _air_aerosol particles_alpha activity conc., long lived_1 month',
            u'417 _air_aerosol particles_alpha activity conc., long lived_1 month'
            u'423 _air_noble gases_gamma activity_1 h',
            u'425 _air_noble gases_gamma activity_1 d',
            u'426 _air_noble gases_gamma activity_1 week',
            u'427 _air_noble gases_gamma activity_1 month',
            u'428 _air_noble gases_gamma activity_3 months',
            u'429 _air_noble gases_gamma activity_1 year',
            u'433 _air_noble gases_total gamma activity_1 h',
            u'435 _air_noble gases_total gamma activity_1 d',
            u'436 _air_noble gases_total gamma activity_1 week',
            u'437 _air_noble gases_total gamma activity_1 month',
            u'438 _air_noble gases_total gamma activity_3 months',
            u'439 _air_noble gases_total gamma activity_1 year',
            u'443 _air_noble gases_beta activity_1 h',
            u'445 _air_noble gases_beta activity_1 d',
            u'446 _air_noble gases_beta activity_1 week',
            u'447 _air_noble gases_beta activity_1 month',
            u'448 _air_noble gases_beta activity_3 months',
            u'449 _air_noble gases_beta activity_1 year',
            u'453 _air_noble gases_total beta activity_1 h',
            u'455 _air_noble gases_total beta activity_1 d',
            u'456 _air_noble gases_total beta activity_1 week',
            u'457 _air_noble gases_total beta activity_1 month',
            u'458 _air_noble gases_total beta activity_3 months',
            u'459 _air_noble gases_total beta activity_1 year',
            u'563 _air_gases_beta activity_1 h',
            u'565 _air_gases_beta activity_1 d',
            u'566 _air_gases_beta activity_1 week',
            u'567 _air_gases_beta activity_1 month',
            u'568 _air_gases_beta activity_3 months',
            u'569 _air_gases_beta activity_1 year',
            u'573 _air_aerosol particles_beta activity,  long lived_1 h',
            u'575 _air_aerosol particles_beta activity,  long lived_1 d',
            u'576 _air_aerosol particles_beta activity,  long lived_1 week',
            u'577 _air_aerosol particles_beta activity,  long lived_1 month',
            u'578 _air_aerosol particles_beta activity,  long lived_3 months',
            u'579 _air_aerosol particles_beta activity,  long lived_1 year',
            u'583 _air__volume_1 h',
            u'585 _air__volume_1 d',
            u'586 _air__volume_1 week',
            u'587 _air__volume_1 month',
            u'588 _air__volume_3 months',
            u'589 _air__volume_1 year',
            u' ____',
            u'591 _air__volume stream_10 min',
            u'592 _air__volume stream_30 min',
            u'593 _air_stack_temperature_10 min',
            u'594 _air_stack_temperature_30 min',
            u'595 _air_stack_temperature_1 h',
            u'596 _air__temperature_10 min',
            u'597 _air__temperature_30 min',
            u'598 _air__temperature_1 h',
            u'599 _air__overall loss factor _',
            u'606 _water__gamma activity_1 week',
            u'607 _water__gamma activity_1 month',
            u'608 _water__gamma activity_3 months',
            u'609 _water__gamma activity_1 year',
            u'623 _water__beta activity_1 h',
            u'625 _water__beta activity_1 d',
            u'626 _water__beta activity_1 week',
            u'627 _water__beta activity_1 month',
            u'628 _water__beta activity_3 months',
            u'629 _water__beta activity_1 year',
            u'646 _water__alpha activity_1 week',
            u'647 _water__alpha activity_1 month',
            u'648 _water__alpha activity_3 months',
            u'649 _water__alpha activity_1 year',
            u'656 _water__total alpha activity_1 week',
            u'657 _water__total alpha activity_1 month',
            u'658 _water__total alpha activity_3 months',
            u'659 _water__total alpha activity_1 year',
            u'661 _water__gamma act.conc._10 min',
            u'662 _water__gamma act.conc._30 min',
            u'663 _water__gamma act.conc._1 h',
            u'664 _water__gamma act.conc._2 h',
            u'665 _water__gamma act.conc._1 d',
            u'671 _water__specific act.conc._10 min',
            u'672 _water__specific act.conc._30 min',
            u'673 _water__specific act.conc._1 h',
            u'674 _water__specific act.conc._2 h',
            u'691 _air__counting rate_10 min',
            u'693 _air__counting rate_1 h',
            u'695 _air__counting rate_1 d',
            u'696 _air__counting rate_1 week',
            u'697 _air__counting rate_1 month',
            u'698 _air__counting rate_3 months',
            u'706 _water__volume_1 week',
            u'707 _water__volume_1 month',
            u'708 _water__volume_3 months',
            u'709 _water__volume_1 year',
            u'711 _water__volume stream_10 min',
            u'712 _water__volume stream_30 min',
            u'716 _water__temperature_10 min',
            u'717 _water__temperature_30 min',
            u'786 _air_meteo_temperature_10 min',
            u'787 _air_meteo_temperature_30 min',
            u'788 _air_meteo_temperature_1 h',
            u'791 __meteo_air pressure_10 min',
            u'793 __meteo_air pressure_1 h',
            u'796 __meteo_rel. humidity_10 min',
            u'797 __meteo_rel. humidity_1 h',
            u'800 __meteo_precipitation_',
            u'801 __meteo_precipitation_10 min',
            u'802 __meteo_precipitation_30 min',
            u'803 __meteo_precipitation_1 h',
            u'804 __meteo_precipitation_2 h',
            u'805 __meteo_precipitation_1 d',
            u'806 __meteo_precipitation_1 wo',
            u'807 __meteo_precipitation_1 m',
            u'815 __meteo_precipitation snow_1 d',
            u'818 __meteo_precipitation probability_15 min',
            u'819 __meteo_precipitation probability_2 h',
            u'824 __meteo_precipitation intensity_',
            u'825 __meteo_precipitation intensity_',
            u'827 __meteo_precipitation relativly_10 min',
            u'831 __meteo_wind velocity_10 min',
            u'832 __meteo_wind velocity_30 min',
            u'833 __meteo_wind velocity_1 h',
            u'834 __meteo_wind velocity_2 h',
            u'836 __meteo_wind veloc. fluctuation (sigma w)_10 min',
            u'837 __meteo_wind veloc. fluctuation (sigma w)_30 min',
            u'838 __meteo_wind veloc. fluctuation (sigma w)_1 h',
            u'841 __meteo_wind direction_10 min',
            u'842 __meteo_wind direction_30 min',
            u'843 __meteo_wind direction_1 h',
            u'844 __meteo_wind direction_2 h',
            u'851 __meteo_wind dir. fluctuation (sigma ?)_10 min',
            u'852 __meteo_wind dir. fluctuation (sigma ?)_30 min',
            u'853 __meteo_wind dir. fluctuation (sigma ?)_1 h',
            u'856 __meteo_wind dir. fluctuation (sigma ?)_10 min',
            u'857 __meteo_wind dir. fluctuation (sigma ?)_30 min',
            u'858 __meteo_wind dir. fluctuation (sigma ?)_1 h',
            u'861 __meteo_radiation balance_10 min',
            u'862 __meteo_radiation balance_30 min',
            u'863 __meteo_radiation balance_1 h',
            u'876 __meteo_stability class (1-6) (sigma w)_10 min',
            u'877 __meteo_stability class (1-6) (sigma w)_30 min',
            u'878 __meteo_stability class (1-6) (sigma w)_1 h',
            u'881 __meteo_stability class (1-6) (radiation balance)_10 min',
            u'882 __meteo_stability class (1-6) (radiation balance)_30 min',
            u'883 __meteo_stability class (1-6) (radiation balance)_1 h',
            u'886 __meteo_stability class (1-6) (sigma ?)_10 min',
            u'887 __meteo_stability class (1-6) (sigma ?)_30 min',
            u'888 __meteo_stability class (1-6) (sigma ?)_1 h',
            u'891 __meteo_stability class (1-6) (sigma ?)_10 min',
            u'892 __meteo_stability class (1-6) (sigma ?)_30 min',
            u'893 __meteo_stability class (1-6) (sigma ?)_1 h',
            u'896 __meteo_stability class (1-6) (temp. gradient)_10 min',
            u'897 __meteo_stability class (1-6) (temp. gradient)_30 min',
            u'898 __meteo_stability class (1-6) (temp. gradient)_1 h',
            u'951 ___electrical power_10 min',
            u'953 ___electrical power_1 h',
            u'955 ___electrical power_1 d',
            u'956 ___electrical power_1 week',
            u'957 ___electrical power_1 month',
            u'958 ___electrical power_3 months',
            u'959 ___electrical power_1 year',
            u'961 ___therm. power_10 min',
            u'963 ___therm. power_1 h',
            u'965 ___therm. power_1 d',
            u'966 ___therm. power_1 week',
            u'967 ___therm. power_1 month',
            u'968 ___therm. power_3 months',
            u'969 ___therm. power_1 year',
        ]
        return safe_simplevocabulary_from_values(values)


DomFactory = Dom()
