from zope.interface import implementer
from zope.schema.interfaces import IVocabularyFactory
from zope.schema.vocabulary import SimpleTerm, SimpleVocabulary


@implementer(IVocabularyFactory)
class SampleType:
    def __call__(self, context=None):
        items = [
            ("A", "Abwasser, Reststoffe und Abfälle"),
            ("A1", "Kläranlage"),
            ("A11", "Abwasser aus Kläranlagenablauf"),
            ("A12", "Wasser aus Kanalisation, Kläranlagenzulauf, Regenrückhaltebecken"),
            ("A13", "Klärschlamm"),
            ("A2", "Verbrennungsanlage"),
            ("A21", "Filterstaub, Filterasche"),
            ("A22", "Kesselasche, Schlacke"),
            ("A23", "Feste Rückstände aus Rauchgaswäsche"),
            ("A24", "Flüssige Rückstände aus Rauchgaswäsche"),
            ("A3", "Mülldeponie"),
            ("A31", "Sicker- und Grundwasser"),
            ("A32", "Deponieoberfläche"),
            ("A4", "Kompostierungsanlage"),
            ("A41", "Kompost"),
            ("A42", "organische Düngemittel (aus landwirtschaftlichen Abfällen)"),
            ("A5", "Spezielle Reststoffe und Abfälle"),
            ("A51", "Luftfilter"),
            ("A52", "Gartenabfälle"),
            ("A53", "Folien"),
            ("A54", "sonstige spezielle Reststoffe und Abfälle"),
            ("A55", "Reststoffe aus der Trinkwasseraufbereitung"),
            ("A56", "Bauschutt"),
            ("B", "Boden"),
            ("B1", "Boden in-situ (flächenbezogene Aktivität)"),
            ("B11", "Boden in-situ (flächenbezogene Aktivität); Boden unversiegelt"),
            ("B12", "Boden in-situ (flächenbezogene Aktivität); Boden versiegelt"),
            ("B13", "Bodenauflage"),
            ("B2", "Boden in-situ (nuklidspezifische Dosisleistung)"),
            ("B21", "Boden in-situ (nuklidspez. Dosisleistung),Boden unversiegelt"),
            ("B22", "Boden in-situ (nuklidspez. Dosisleistung),Boden versiegelt"),
            ("B3", "Weide-/ Acker-/ Wald-/ Freizeitflächen-/ Ödland- und Gartenböden"),
            ("B31", "Weideböden"),
            ("B32", "Ackerböden"),
            ("B33", "Waldböden"),
            ("B34", "Freizeitflächenböden"),
            ("B35", "Ödlandböden, Brachen"),
            ("B36", "Gartenböden"),
            ("F", "Futtermittel"),
            ("F1", "Grünfutter (einschl. Weide- und Wiesenbewuchs)"),
            ("F11", "Weide- u. Wiesenbewuchs"),
            ("F12", "Grünfutterpflanzen (außer Weide- u. Wiesenbewuchs)"),
            ("F2", "Mais"),
            ("F21", "Mais (ganze Pflanze)"),
            ("F3", "Futtergetreide"),
            ("F31", "Futtergetreide (einschl. Maiskörner)"),
            ("F4", "Hackfrüchte"),
            ("F41", "Futterkartoffeln und Futterrüben"),
            ("F5", "Heu, Stroh, Cobs, Trockenmehle"),
            ("F51", "Heu"),
            ("F52", "Stroh, Cobs, Trockenmehle"),
            ("F5Z", "Sonstige Futtermittel"),
            ("F6", "Mischfuttermittelrohstoffe"),
            ("F61", "Maisprodukte"),
            ("F62", "Schrote"),
            ("F63", "Maniok und Tapioka"),
            ("F7", "Mischfuttermittel"),
            ("F71", "Kraftfuttermischungen"),
            ("G", "Gewässer"),
            ("G1", "Fließgewässer"),
            ("G11", "Wasser in Fließgewässern"),
            ("G12", "Schwebstoff in Fließgewässern"),
            ("G13", "Sediment in Fließgewässern"),
            ("G2", "Stehende Gewässer"),
            ("G21", "Wasser in stehenden Gewässern"),
            ("G22", "Schwebstoffe in stehenden Gewässern"),
            ("G23", "Sedimente in stehenden Gewässern"),
            ("G3", "Meer"),
            ("G31", "Meerwasser"),
            ("G32", "Schwebstoffe im Meerwasser"),
            ("G33", "Sedimente im Meerwasser"),
            ("G4", "Grundwasser"),
            ("G41", "Grundwasser (nicht zur Trinkwassergewinnung)"),
            ("G5", "Rohwasser zur Trinkwassergewinnung"),
            ("G51", "Rohwasser, geschützt, aus Grund- und Tiefenwasser"),
            ("G52", "Rohwasser, ungeschützt, aus Oberflächenwasser"),
            ("G53", "Zisternenwasser"),
            ("GZ", "Sonstige Wässer"),
            ("GZ1", "Wasser zur Viehtränke"),
            ("I", "Bio-Indikatoren, Tabak und Arzneimittel"),
            ("I1", "Pflanzliche Indikatoren"),
            ("I11", "Blätter"),
            ("I12", "Nadeln"),
            ("I13", "Gras"),
            ("I14", "Moose, Farne, Flechten u. Heidekraut"),
            ("I15", "Wasserpflanzen"),
            ("I19", "Gras (REI)"),
            ("I2", "Tabak"),
            ("I21", "Tabakblätter"),
            ("I22", "Zigaretten, Zigarren"),
            ("I3", "Arzneimittel"),
            ("I31", "Ausgangsstoffe für Arzneimittel"),
            ("I32", "Arzneimittelprodukte"),
            ("L", "Luft und Niederschlag"),
            ("L1", "Luft/Gammastrahlung"),
            ("L11", "Gamma-Ortsdosis"),
            ("L12", "Gamma-Ortsdosisleistung"),
            ("L2", "Luft/Neutronenstrahlung"),
            ("L21", "Neutronen-Ortsdosis"),
            ("L22", "Neutronen-Ortsdosisleistung"),
            ("L3", "Luft/Aerosole"),
            ("L31", "Aerosole"),
            ("L32", "Bilanzierungsmessung Aerosole"),
            ("L4", "Luft/gasförmige Komponenten (einschl. Iod)"),
            ("L41", "Luft/gasförmiges Iod"),
            ("L42", "Luft/Edelgase"),
            ("L43", "andere gasförmige Komponenten (außer Iod u. Edelgase)"),
            ("L44", "Bilanzierungsmessung Luft/Iod"),
            ("L45", "Bilanzierungsmessung Luft/Edelgase"),
            (
                "L46",
                "Bilanzierungsmessung andere gasförmige Komponenten (außer Iod und Edelgase)",
            ),
            ("L5", "Niederschlag"),
            ("L51", "Niederschlag (Aktivitätskonzentration)"),
            ("L52", "nasse Niederschläge (Deposition)"),
            ("L53", "trockene Niederschläge (Deposition)"),
            ("L54", "Niederschlagsmenge"),
            ("L6", "Spurenmessung Luft"),
            ("L61", "Spurenmessung Luft - Aerosole"),
            ("L62", "Spurenmessung Luft - gasförmige Komponenten (einschl. Iod)"),
            ("L63", "Spurenmessung Luft - Edelgase"),
            ("M", "Meteo-Umweltbereich"),
            ("N", "Nahrungsmittel (einschl. Trinkwasser)"),
            ("N1", "Milch"),
            ("N11", "Sammelmilch (Kuh-)"),
            ("N12", "Hofmilch (Kuh-)"),
            ("N13", "bearbeitete Trinkmilch (Kuh-)"),
            ("N14", "Milch anderer Tiere (Schaf, Ziege, Stute)"),
            ("N15", "Humanmilch"),
            ("N2", "Frischgemüse (einschl. Kartoffeln und Pilze)"),
            ("N21", "Blattgemüse, ungeschützter Anbau"),
            ("N22", "Wurzelgemüse, ungeschützter Anbau"),
            ("N23", "Fruchtgemüse, ungeschützter Anbau"),
            ("N24", "Sprossgemüse, ungeschützter Anbau"),
            ("N25", "Kartoffeln"),
            ("N26", "Blattgemüse, geschützter Anbau"),
            ("N27", "Wurzelgemüse, geschützter Anbau"),
            ("N28", "Fruchtgemüse, geschützter Anbau"),
            ("N29", "Sprossgemüse, geschützter Anbau"),
            ("N2A", "Wildpilze"),
            ("N2B", "Kulturpilze"),
            ("N2C", "Sonstige Wildpilze"),
            ("N2Y", "Sonstiges Gemüse, ungeschützter Anbau"),
            ("N2Z", "Sonstiges Gemüse, geschützter Anbau"),
            ("N3", "Getreide"),
            (
                "N31",
                "Getreidekörner (Weizen-,Roggen-, Gersten-, Hafer-, Mais-, Triticalenkörner)",
            ),
            ("N3Z", "Sonstige Getreidearten"),
            ("N4", "Obst"),
            ("N41", "Schalenobst (Nüsse)"),
            ("N42", "Kernobst"),
            ("N43", "Steinobst"),
            ("N44", "Beerenobst, ungeschützter Anbau (außer Wald-/Wildbeeren)"),
            ("N45", "Beerenobst, geschützter Anbau"),
            ("N46", "Wald-/Wildbeeren"),
            ("N4Z", "Sonstige Obstarten"),
            ("N5", "Fleisch"),
            ("N51", "Rindfleisch"),
            ("N52", "Kalbfleisch"),
            ("N53", "Schweinefleisch"),
            ("N54", "Geflügelfleisch"),
            ("N55", "Lammfleisch"),
            ("N56", "Haarwildfleisch"),
            ("N5Z", "Sonstiges Fleisch"),
            ("N6", "Fisch und Meeresfrüchte"),
            ("N61", "Süßwasserfisch"),
            ("N62", "Seefisch"),
            ("N63", "Meeresfrüchte"),
            ("N64", "Fischerzeugnisse"),
            ("N65", "Wasserpflanzen, Trockenprodukte"),
            ("N7", "Trinkwasser"),
            ("N71", "Reinwasser aus geschützten Rohwasservorkommen"),
            ("N72", "Reinwasser aus ungeschützten Rohwasservorkommen"),
            ("N73", "Reinwasser aus Mischrohwasser"),
            ("N74", "Rohwasser, geschützt, aus Grund- und Tiefenwasser (ungültig)"),
            ("N75", "Rohwasser, ungeschützt, aus Oberflächenwasser (ungültig)"),
            ("N76", "Zisternenwasser (ungültig)"),
            ("N8", "Gesamtnahrung, Fertiggerichte und Getränke"),
            ("N81", "Gesamtnahrung"),
            ("N82", "Säuglings- und Kleinkindernahrung"),
            ("N83", "Fertiggerichte, verzehrsfertig (einschl. Suppen)"),
            ("N84", "Fertiggerichte, Trockensubstanz (einschl. Suppen)"),
            (
                "N85",
                "Getränke, trinkfertig, nicht alkoholisch (einschl. Tee und Kaffee)",
            ),
            (
                "N86",
                "Getränke, Trockensubstanz, nicht alkoholisch (einschl. Tee und Kaffee)",
            ),
            ("N87", "Getränke, alkoholisch"),
            ("N9", "Nahrungsmittelprodukte"),
            ("N91", "Käse aus Kuhmilch"),
            ("N92", "Käse aus Milch anderer Tiere"),
            ("N93", "Milchprodukte außer Käse, Frischprodukte"),
            ("N94", "Milchprodukte außer Käse, Trockenprodukte"),
            ("N95", "Milchprodukte außer Käse, haltbar gemacht"),
            (
                "N96",
                "Gemüseprodukte einschl. Kartoffeln, Frischprodukte auch tiefgefroren",
            ),
            ("N97", "Gemüseprodukte einschl. Kartoffeln, Trockenprodukte"),
            ("N98", "Gemüseprodukte einschl. Kartoffeln, haltbar gemacht"),
            ("N99", "Wildpilzprodukte, Frischprodukte auch tiefgefroren"),
            ("N9A", "Wildpilzprodukte, Trockenprodukte"),
            ("N9B", "Wildpilzprodukte, haltbar gemacht"),
            ("N9C", "Kulturpilzprodukte, Frischprodukte auch tiefgefroren"),
            ("N9D", "Kulturpilzprodukte, Trockenprodukte"),
            ("N9E", "Kulturpilzprodukte, haltbar gemacht"),
            ("N9F", "Getreideprodukte außer Brot"),
            ("N9G", "Brote und Gebäcke"),
            ("N9H", "Obstprodukte, Frischprodukte auch tiefgefroren"),
            ("N9I", "Obstprodukte, Trockenprodukte"),
            ("N9J", "Obstprodukte, haltbar gemacht"),
            (
                "N9K",
                "Fleischprodukte u. Wurstwaren, ohne Wild, Frischprod. auch tiefgefr.",
            ),
            ("N9L", "Fleischprodukte u. Wurstwaren, ohne Wild, haltbar gemacht"),
            ("N9M", "Wildfleischprodukte u. -wurstwaren, Frischprod. auch tiefgefr."),
            ("N9N", "Wildfleischprodukte u. -wurstwaren, haltbar gemacht"),
            ("N9O", "Fischprodukte, Frischprod. auch tiefgefr."),
            ("N9P", "Fischprodukte, haltbar gemacht"),
            ("N9Q", "Meeresfrüchteprodukte, Frischprod. auch tiefgefr."),
            ("N9R", "Meeresfrüchteprodukte, haltbar gemacht"),
            ("NZ", "Sonstige Nahrungsmittel"),
            ("NZ1", "Hühnereier"),
            ("NZ2", "Honig"),
            ("NZ3", "weitere Nahrungsmittel"),
            ("S", "Umweltbereiche für Störfall"),
            ("S1", "Luft - Störfall"),
            ("S11", "Luft/äußere Strahlung (Gamma-ODL) - Störfall"),
            ("S12", "Luft/Aerosole - Störfall"),
            ("S13", "Luft/gasförmiges Iod - Störfall"),
            ("S14", "Luft/äußere Strahlung (Gamma-OD) -Störfall"),
            ("S2", "Boden/-Oberfläche - Störfall"),
            (
                "S21",
                "Bodenoberfläche (unversiegelt, in-situ, flächenbezogene Aktivität) - Störfall",
            ),
            ("S22", "Boden - Störfall"),
            (
                "S23",
                "Bodenoberfläche (versiegelt, in-situ, flächenbezogene Aktivität) - Störfall",
            ),
            ("S3", "Pflanzen/Bewuchs - Störfall"),
            ("S31", "Weide- und Wiesenbewuchs - Störfall"),
            ("S32", "Grünfutterpflanzen (außer Weide- und Wiesenbewuchs) - Störfall"),
            ("S4", "Oberirdische Gewässer - Störfall"),
            ("S41", "Oberflächenwasser (Fließgewässer) - Störfall"),
            ("S42", "Oberflächenwasser (stehende Gewässer) - Störfall"),
            ("S43", "Oberflächenwasser (Viehtränke) - Störfall"),
            ("SF1", "Rindfleisch - Störfall"),
            ("SF2", "Kalbfleisch - Störfall"),
            ("SF3", "Schweinefleisch - Störfall"),
            ("SF4", "Geflügelfleisch - Störfall"),
            ("SF5", "Lammfleisch - Störfall"),
            ("SG1", "Blattgemüse, ungeschützter Anbau - Störfall"),
            ("SG2", "Wurzelgemüse, ungeschützter Anbau - Störfall"),
            ("SG3", "Fruchtgemüse, ungeschützter Anbau - Störfall"),
            ("SG4", "Sprossgemüse, ungeschützter Anbau - Störfall"),
            ("SG5", "Kartoffeln - Störfall"),
            (
                "SG6",
                "Getreidekörner (Weizen, Roggen, Gerste, Hafer, Mais, Triticale) - Störfall",
            ),
            ("SO1", "Schalenobst (Nüsse) - Störfall"),
            ("SO2", "Kernobst - Störfall"),
            ("SO3", "Steinobst - Störfall"),
            ("SO4", "Beerenobst (außer Wald-/Wildbeeren) - Störfall"),
            ("SO5", "Sonstige Obstarten - Störfall"),
            ("Z", "Sonstige Mediengruppen"),
            ("Z1", "Baustoffe"),
            ("Z11", "mineralische Ausgangsstoffe für Baustoffe"),
            ("Z12", "verarbeitete mineralische Baustoffe"),
            ("Z13", "organische Ausgangsstoffe für Baustoffe"),
            ("Z14", "verarbeitete organische Baustoffe"),
            ("Z2", "Bodenschätze"),
            ("Z21", "Rohgas"),
            ("Z22", "Reingas"),
            ("Z3", "Bedarfsgegenstände und Kosmetische Mittel"),
            ("Z31", "Bedarfsgegenstände mit Lebensmittelkontakt"),
            (
                "Z32",
                "Bedarfsgegenstände zur Verpackung von Tabakerz. und kosmet. Mitteln",
            ),
            ("Z33", "Bedarfsgegenstände mit Körperkontakt/ Spielwaren/ Kleidung"),
            ("Z34", "Bedarfsgegenstände zur Reinigung und Pflege"),
            ("Z35", "Kosmetische Mittel und Stoffe zu deren Herstellung"),
        ]
        terms = [SimpleTerm(value, value, f"{value} {title}") for value, title in items]
        return SimpleVocabulary(terms)


SampleTypeFactory = SampleType()
