# -*- coding: utf-8 -*-

# from plone import api
from docpool.doksys import _
from plone.dexterity.interfaces import IDexterityContent
from zope.globalrequest import getRequest
from zope.interface import implementer
from zope.schema.interfaces import IVocabularyFactory
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary


class VocabItem(object):
    def __init__(self, token, value):
        self.token = token
        self.value = value


@implementer(IVocabularyFactory)
class SampleTypeIds(object):
    """
    """

    def __call__(self, context):
        # Just an example list of content for our vocabulary,
        # this can be any static or dynamic data, a catalog result for example.
        items = [
            VocabItem(u'9', _(u'9')),
            VocabItem(u'91', _(u'91')),
            VocabItem(u'A', _(u'A')),
            VocabItem(u'A1', _(u'A1')),
            VocabItem(u'A11', _(u'A11')),
            VocabItem(u'A12', _(u'A12')),
            VocabItem(u'A13', _(u'A13')),
            VocabItem(u'A2', _(u'A2')),
            VocabItem(u'A21', _(u'A21')),
            VocabItem(u'A22', _(u'A22')),
            VocabItem(u'A23', _(u'A23')),
            VocabItem(u'A24', _(u'A24')),
            VocabItem(u'A3', _(u'A3')),
            VocabItem(u'A31', _(u'A31')),
            VocabItem(u'A32', _(u'A32')),
            VocabItem(u'A4', _(u'A4')),
            VocabItem(u'A41', _(u'A41')),
            VocabItem(u'A42', _(u'A42')),
            VocabItem(u'A5', _(u'A5')),
            VocabItem(u'A51', _(u'A51')),
            VocabItem(u'A52', _(u'A52')),
            VocabItem(u'A53', _(u'A53')),
            VocabItem(u'A54', _(u'A54')),
            VocabItem(u'A55', _(u'A55')),
            VocabItem(u'A56', _(u'A56')),
            VocabItem(u'B', _(u'B')),
            VocabItem(u'B1', _(u'B1')),
            VocabItem(u'B11', _(u'B11')),
            VocabItem(u'B12', _(u'B12')),
            VocabItem(u'B13', _(u'B13')),
            VocabItem(u'B2', _(u'B2')),
            VocabItem(u'B21', _(u'B21')),
            VocabItem(u'B22', _(u'B22')),
            VocabItem(u'B3', _(u'B3')),
            VocabItem(u'B31', _(u'B31')),
            VocabItem(u'B32', _(u'B32')),
            VocabItem(u'B33', _(u'B33')),
            VocabItem(u'B34', _(u'B34')),
            VocabItem(u'B35', _(u'B35')),
            VocabItem(u'B36', _(u'B36')),
            VocabItem(u'F', _(u'F')),
            VocabItem(u'F1', _(u'F1')),
            VocabItem(u'F11', _(u'F11')),
            VocabItem(u'F12', _(u'F12')),
            VocabItem(u'F2', _(u'F2')),
            VocabItem(u'F21', _(u'F21')),
            VocabItem(u'F3', _(u'F3')),
            VocabItem(u'F31', _(u'F31')),
            VocabItem(u'F4', _(u'F4')),
            VocabItem(u'F41', _(u'F41')),
            VocabItem(u'F5', _(u'F5')),
            VocabItem(u'F51', _(u'F51')),
            VocabItem(u'F52', _(u'F52')),
            VocabItem(u'F5Z', _(u'F5Z')),
            VocabItem(u'F6', _(u'F6')),
            VocabItem(u'F61', _(u'F61')),
            VocabItem(u'F62', _(u'F62')),
            VocabItem(u'F63', _(u'F63')),
            VocabItem(u'F7', _(u'F7')),
            VocabItem(u'F71', _(u'F71')),
            VocabItem(u'G', _(u'G')),
            VocabItem(u'G1', _(u'G1')),
            VocabItem(u'G11', _(u'G11')),
            VocabItem(u'G12', _(u'G12')),
            VocabItem(u'G13', _(u'G13')),
            VocabItem(u'G2', _(u'G2')),
            VocabItem(u'G21', _(u'G21')),
            VocabItem(u'G22', _(u'G22')),
            VocabItem(u'G23', _(u'G23')),
            VocabItem(u'G3', _(u'G3')),
            VocabItem(u'G31', _(u'G31')),
            VocabItem(u'G32', _(u'G32')),
            VocabItem(u'G33', _(u'G33')),
            VocabItem(u'G4', _(u'G4')),
            VocabItem(u'G41', _(u'G41')),
            VocabItem(u'G5', _(u'G5')),
            VocabItem(u'G51', _(u'G51')),
            VocabItem(u'G52', _(u'G52')),
            VocabItem(u'G53', _(u'G53')),
            VocabItem(u'GZ', _(u'GZ')),
            VocabItem(u'GZ1', _(u'GZ1')),
            VocabItem(u'I', _(u'I')),
            VocabItem(u'I1', _(u'I1')),
            VocabItem(u'I11', _(u'I11')),
            VocabItem(u'I12', _(u'I12')),
            VocabItem(u'I13', _(u'I13')),
            VocabItem(u'I14', _(u'I14')),
            VocabItem(u'I15', _(u'I15')),
            VocabItem(u'I19', _(u'I19')),
            VocabItem(u'I2', _(u'I2')),
            VocabItem(u'I21', _(u'I21')),
            VocabItem(u'I22', _(u'I22')),
            VocabItem(u'I3', _(u'I3')),
            VocabItem(u'I31', _(u'I31')),
            VocabItem(u'I32', _(u'I32')),
            VocabItem(u'L', _(u'L')),
            VocabItem(u'L1', _(u'L1')),
            VocabItem(u'L11', _(u'L11')),
            VocabItem(u'L12', _(u'L12')),
            VocabItem(u'L2', _(u'L2')),
            VocabItem(u'L21', _(u'L21')),
            VocabItem(u'L22', _(u'L22')),
            VocabItem(u'L3', _(u'L3')),
            VocabItem(u'L31', _(u'L31')),
            VocabItem(u'L32', _(u'L32')),
            VocabItem(u'L4', _(u'L4')),
            VocabItem(u'L41', _(u'L41')),
            VocabItem(u'L42', _(u'L42')),
            VocabItem(u'L43', _(u'L43')),
            VocabItem(u'L44', _(u'L44')),
            VocabItem(u'L45', _(u'L45')),
            VocabItem(u'L46', _(u'L46')),
            VocabItem(u'L5', _(u'L5')),
            VocabItem(u'L51', _(u'L51')),
            VocabItem(u'L52', _(u'L52')),
            VocabItem(u'L53', _(u'L53')),
            VocabItem(u'L54', _(u'L54')),
            VocabItem(u'L6', _(u'L6')),
            VocabItem(u'L61', _(u'L61')),
            VocabItem(u'L62', _(u'L62')),
            VocabItem(u'L63', _(u'L63')),
            VocabItem(u'M', _(u'M')),
            VocabItem(u'N', _(u'N')),
            VocabItem(u'N1', _(u'N1')),
            VocabItem(u'N11', _(u'N11')),
            VocabItem(u'N12', _(u'N12')),
            VocabItem(u'N13', _(u'N13')),
            VocabItem(u'N14', _(u'N14')),
            VocabItem(u'N15', _(u'N15')),
            VocabItem(u'N2', _(u'N2')),
            VocabItem(u'N21', _(u'N21')),
            VocabItem(u'N22', _(u'N22')),
            VocabItem(u'N23', _(u'N23')),
            VocabItem(u'N24', _(u'N24')),
            VocabItem(u'N25', _(u'N25')),
            VocabItem(u'N26', _(u'N26')),
            VocabItem(u'N27', _(u'N27')),
            VocabItem(u'N28', _(u'N28')),
            VocabItem(u'N29', _(u'N29')),
            VocabItem(u'N2A', _(u'N2A')),
            VocabItem(u'N2B', _(u'N2B')),
            VocabItem(u'N2C', _(u'N2C')),
            VocabItem(u'N2Y', _(u'N2Y')),
            VocabItem(u'N2Z', _(u'N2Z')),
            VocabItem(u'N3', _(u'N3')),
            VocabItem(u'N31', _(u'N31')),
            VocabItem(u'N3Z', _(u'N3Z')),
            VocabItem(u'N4', _(u'N4')),
            VocabItem(u'N41', _(u'N41')),
            VocabItem(u'N42', _(u'N42')),
            VocabItem(u'N43', _(u'N43')),
            VocabItem(u'N44', _(u'N44')),
            VocabItem(u'N45', _(u'N45')),
            VocabItem(u'N46', _(u'N46')),
            VocabItem(u'N4Z', _(u'N4Z')),
            VocabItem(u'N5', _(u'N5')),
            VocabItem(u'N51', _(u'N51')),
            VocabItem(u'N52', _(u'N52')),
            VocabItem(u'N53', _(u'N53')),
            VocabItem(u'N54', _(u'N54')),
            VocabItem(u'N55', _(u'N55')),
            VocabItem(u'N56', _(u'N56')),
            VocabItem(u'N5Z', _(u'N5Z')),
            VocabItem(u'N6', _(u'N6')),
            VocabItem(u'N61', _(u'N61')),
            VocabItem(u'N62', _(u'N62')),
            VocabItem(u'N63', _(u'N63')),
            VocabItem(u'N64', _(u'N64')),
            VocabItem(u'N65', _(u'N65')),
            VocabItem(u'N7', _(u'N7')),
            VocabItem(u'N71', _(u'N71')),
            VocabItem(u'N72', _(u'N72')),
            VocabItem(u'N73', _(u'N73')),
            VocabItem(u'N74', _(u'N74')),
            VocabItem(u'N75', _(u'N75')),
            VocabItem(u'N76', _(u'N76')),
            VocabItem(u'N8', _(u'N8')),
            VocabItem(u'N81', _(u'N81')),
            VocabItem(u'N82', _(u'N82')),
            VocabItem(u'N83', _(u'N83')),
            VocabItem(u'N84', _(u'N84')),
            VocabItem(u'N85', _(u'N85')),
            VocabItem(u'N86', _(u'N86')),
            VocabItem(u'N87', _(u'N87')),
            VocabItem(u'N9', _(u'N9')),
            VocabItem(u'N91', _(u'N91')),
            VocabItem(u'N92', _(u'N92')),
            VocabItem(u'N93', _(u'N93')),
            VocabItem(u'N94', _(u'N94')),
            VocabItem(u'N95', _(u'N95')),
            VocabItem(u'N96', _(u'N96')),
            VocabItem(u'N97', _(u'N97')),
            VocabItem(u'N98', _(u'N98')),
            VocabItem(u'N99', _(u'N99')),
            VocabItem(u'N9A', _(u'N9A')),
            VocabItem(u'N9B', _(u'N9B')),
            VocabItem(u'N9C', _(u'N9C')),
            VocabItem(u'N9D', _(u'N9D')),
            VocabItem(u'N9E', _(u'N9E')),
            VocabItem(u'N9F', _(u'N9F')),
            VocabItem(u'N9G', _(u'N9G')),
            VocabItem(u'N9H', _(u'N9H')),
            VocabItem(u'N9I', _(u'N9I')),
            VocabItem(u'N9J', _(u'N9J')),
            VocabItem(u'N9K', _(u'N9K')),
            VocabItem(u'N9L', _(u'N9L')),
            VocabItem(u'N9M', _(u'N9M')),
            VocabItem(u'N9N', _(u'N9N')),
            VocabItem(u'N9O', _(u'N9O')),
            VocabItem(u'N9P', _(u'N9P')),
            VocabItem(u'N9Q', _(u'N9Q')),
            VocabItem(u'N9R', _(u'N9R')),
            VocabItem(u'NZ', _(u'NZ')),
            VocabItem(u'NZ1', _(u'NZ1')),
            VocabItem(u'NZ2', _(u'NZ2')),
            VocabItem(u'NZZ', _(u'NZZ')),
            VocabItem(u'S', _(u'S')),
            VocabItem(u'S1', _(u'S1')),
            VocabItem(u'S11', _(u'S11')),
            VocabItem(u'S12', _(u'S12')),
            VocabItem(u'S13', _(u'S13')),
            VocabItem(u'S14', _(u'S14')),
            VocabItem(u'S2', _(u'S2')),
            VocabItem(u'S21', _(u'S21')),
            VocabItem(u'S22', _(u'S22')),
            VocabItem(u'S23', _(u'S23')),
            VocabItem(u'S3', _(u'S3')),
            VocabItem(u'S31', _(u'S31')),
            VocabItem(u'S32', _(u'S32')),
            VocabItem(u'S4', _(u'S4')),
            VocabItem(u'S41', _(u'S41')),
            VocabItem(u'S42', _(u'S42')),
            VocabItem(u'S43', _(u'S43')),
            VocabItem(u'SF1', _(u'SF1')),
            VocabItem(u'SF2', _(u'SF2')),
            VocabItem(u'SF3', _(u'SF3')),
            VocabItem(u'SF4', _(u'SF4')),
            VocabItem(u'SF5', _(u'SF5')),
            VocabItem(u'SG1', _(u'SG1')),
            VocabItem(u'SG2', _(u'SG2')),
            VocabItem(u'SG3', _(u'SG3')),
            VocabItem(u'SG4', _(u'SG4')),
            VocabItem(u'SG5', _(u'SG5')),
            VocabItem(u'SG6', _(u'SG6')),
            VocabItem(u'SO1', _(u'SO1')),
            VocabItem(u'SO2', _(u'SO2')),
            VocabItem(u'SO3', _(u'SO3')),
            VocabItem(u'SO4', _(u'SO4')),
            VocabItem(u'SO5', _(u'SO5')),
            VocabItem(u'Z', _(u'Z')),
            VocabItem(u'Z1', _(u'Z1')),
            VocabItem(u'Z11', _(u'Z11')),
            VocabItem(u'Z12', _(u'Z12')),
            VocabItem(u'Z13', _(u'Z13')),
            VocabItem(u'Z14', _(u'Z14')),
            VocabItem(u'Z2', _(u'Z2')),
            VocabItem(u'Z21', _(u'Z21')),
            VocabItem(u'Z22', _(u'Z22')),
            VocabItem(u'Z3', _(u'Z3')),
            VocabItem(u'Z31', _(u'Z31')),
            VocabItem(u'Z32', _(u'Z32')),
            VocabItem(u'Z33', _(u'Z33')),
            VocabItem(u'Z34', _(u'Z34')),
            VocabItem(u'Z35', _(u'Z35'))
        ]

        # Fix context if you are using the vocabulary in DataGridField.
        # See https://github.com/collective/collective.z3cform.datagridfield/issues/31:  # NOQA: 501
        if not IDexterityContent.providedBy(context):
            req = getRequest()
            context = req.PARENTS[0]

        # create a list of SimpleTerm items:
        terms = []
        for item in items:
            terms.append(
                SimpleTerm(
                    value=item.token,
                    token=item.token.encode('utf'),
                    title=item.value,
                )
            )
        # Create a SimpleVocabulary from the terms list and return it:
        return SimpleVocabulary(terms)


SampleTypeIdFactory = SampleTypeIds()
