# -*- coding: utf-8 -*-

# from plone import api
from docpool.doksys import _
from plone.dexterity.interfaces import IDexterityContent
from zope.globalrequest import getRequest
from zope.interface import implementer
from zope.schema.interfaces import IVocabularyFactory
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary


class VocabItem(object):
    def __init__(self, token, value):
        self.token = token
        self.value = value


@implementer(IVocabularyFactory)
class SampleTypes(object):
    """
    """

    def __call__(self, context):
        # Just an example list of content for our vocabulary,
        # this can be any static or dynamic data, a catalog result for example.
        items = [
            VocabItem(u'PARK', _(u'PARK')),
            VocabItem(u'PARK Modellbereiche', _(u'PARK Modellbereiche')),
            VocabItem(u'Abwasser, Reststoffe  und Abfälle', _(u'Abwasser, Reststoffe  und Abfälle')),
            VocabItem(u'Kläranlage', _(u'Kläranlage')),
            VocabItem(u'Abwasser aus Kläranlagenablauf', _(u'Abwasser aus Kläranlagenablauf')),
            VocabItem(u'Wasser aus Kanalisation, Kläranlagenzulauf, Regenrückhaltebecken',
                      _(u'Wasser aus Kanalisation, Kläranlagenzulauf, Regenrückhaltebecken')),
            VocabItem(u'Klärschlamm', _(u'Klärschlamm')),
            VocabItem(u'Verbrennungsanlage', _(u'Verbrennungsanlage')),
            VocabItem(u'Filterstaub, Filterasche', _(u'Filterstaub, Filterasche')),
            VocabItem(u'Kesselasche, Schlacke', _(u'Kesselasche, Schlacke')),
            VocabItem(u'Feste Rückstände aus Rauchgaswäsche', _(u'Feste Rückstände aus Rauchgaswäsche')),
            VocabItem(u'Flüssige Rückstände aus Rauchgaswäsche', _(u'Flüssige Rückstände aus Rauchgaswäsche')),
            VocabItem(u'Mülldeponie', _(u'Mülldeponie')),
            VocabItem(u'Sicker- und Grundwasser', _(u'Sicker- und Grundwasser')),
            VocabItem(u'Deponieoberfläche', _(u'Deponieoberfläche')),
            VocabItem(u'Kompostierungsanlage', _(u'Kompostierungsanlage')),
            VocabItem(u'Kompost', _(u'Kompost')),
            VocabItem(u'organische Düngemittel (aus landwirtschaftlichen Abfällen)',
                      _(u'organische Düngemittel (aus landwirtschaftlichen Abfällen)')),
            VocabItem(u'Spezielle Reststoffe und Abfälle', _(u'Spezielle Reststoffe und Abfälle')),
            VocabItem(u'Luftfilter', _(u'Luftfilter')),
            VocabItem(u'Gartenabfälle', _(u'Gartenabfälle')),
            VocabItem(u'Folien', _(u'Folien')),
            VocabItem(u'sonstige spezielle Reststoffe und Abfälle', _(u'sonstige spezielle Reststoffe und Abfälle')),
            VocabItem(u'Reststoffe aus der Trinkwasseraufbereitung', _(u'Reststoffe aus der Trinkwasseraufbereitung')),
            VocabItem(u'Bauschutt', _(u'Bauschutt')),
            VocabItem(u'Boden', _(u'Boden')),
            VocabItem(u'Boden in-situ (flächenbezogene Aktivität)', _(u'Boden in-situ (flächenbezogene Aktivität)')),
            VocabItem(u'Boden in-situ (flächenbezogene Aktivität); Boden unversiegelt',
                      _(u'Boden in-situ (flächenbezogene Aktivität); Boden unversiegelt')),
            VocabItem(u'Boden in-situ (flächenbezogene Aktivität); Boden versiegelt',
                      _(u'Boden in-situ (flächenbezogene Aktivität); Boden versiegelt')),
            VocabItem(u'Bodenauflage', _(u'Bodenauflage')),
            VocabItem(u'Boden in-situ (nuklidspezifische Dosisleistung)',
                      _(u'Boden in-situ (nuklidspezifische Dosisleistung)')),
            VocabItem(u'Boden in-situ (nuklidspez. Dosisleistung),Boden unversiegelt',
                      _(u'Boden in-situ (nuklidspez. Dosisleistung),Boden unversiegelt')),
            VocabItem(u'Boden in-situ (nuklidspez. Dosisleistung),Boden versiegelt',
                      _(u'Boden in-situ (nuklidspez. Dosisleistung),Boden versiegelt')),
            VocabItem(u'Weide-/ Acker-/ Wald-/ Freizeitflächen-/ Ödland- und Gartenböden',
                      _(u'Weide-/ Acker-/ Wald-/ Freizeitflächen-/ Ödland- und Gartenböden')),
            VocabItem(u'Weideböden', _(u'Weideböden')),
            VocabItem(u'Ackerböden', _(u'Ackerböden')),
            VocabItem(u'Waldböden', _(u'Waldböden')),
            VocabItem(u'Freizeitflächenböden', _(u'Freizeitflächenböden')),
            VocabItem(u'Ödlandböden, Brachen', _(u'Ödlandböden, Brachen')),
            VocabItem(u'Gartenböden', _(u'Gartenböden')),
            VocabItem(u'Futtermittel', _(u'Futtermittel')),
            VocabItem(u'Grünfutter (einschl. Weide- und Wiesenbewuchs)',
                      _(u'Grünfutter (einschl. Weide- und Wiesenbewuchs)')),
            VocabItem(u'Weide- u. Wiesenbewuchs', _(u'Weide- u. Wiesenbewuchs')),
            VocabItem(u'Grünfutterpflanzen (außer Weide- u. Wiesenbewuchs)',
                      _(u'Grünfutterpflanzen (außer Weide- u. Wiesenbewuchs)')),
            VocabItem(u'Mais', _(u'Mais')),
            VocabItem(u'Mais (ganze Pflanze)', _(u'Mais (ganze Pflanze)')),
            VocabItem(u'Futtergetreide', _(u'Futtergetreide')),
            VocabItem(u'Futtergetreide (einschl. Maiskörner)', _(u'Futtergetreide (einschl. Maiskörner)')),
            VocabItem(u'Hackfrüchte', _(u'Hackfrüchte')),
            VocabItem(u'Futterkartoffeln und Futterrüben', _(u'Futterkartoffeln und Futterrüben')),
            VocabItem(u'Heu, Stroh, Cobs, Trockenmehle', _(u'Heu, Stroh, Cobs, Trockenmehle')),
            VocabItem(u'Heu', _(u'Heu')),
            VocabItem(u'Stroh, Cobs, Trockenmehle', _(u'Stroh, Cobs, Trockenmehle')),
            VocabItem(u'Sonstige Futtermittel', _(u'Sonstige Futtermittel')),
            VocabItem(u'Mischfuttermittelrohstoffe', _(u'Mischfuttermittelrohstoffe')),
            VocabItem(u'Maisprodukte', _(u'Maisprodukte')),
            VocabItem(u'Schrote', _(u'Schrote')),
            VocabItem(u'Maniok und Tapioka', _(u'Maniok und Tapioka')),
            VocabItem(u'Mischfuttermittel', _(u'Mischfuttermittel')),
            VocabItem(u'Kraftfuttermischungen', _(u'Kraftfuttermischungen')),
            VocabItem(u'Gewässer', _(u'Gewässer')),
            VocabItem(u'Fließgewässer', _(u'Fließgewässer')),
            VocabItem(u'Wasser in Fließgewässern', _(u'Wasser in Fließgewässern')),
            VocabItem(u'Schwebstoff in Fließgewässern', _(u'Schwebstoff in Fließgewässern')),
            VocabItem(u'Sediment in Fließgewässern', _(u'Sediment in Fließgewässern')),
            VocabItem(u'Stehende Gewässer', _(u'Stehende Gewässer')),
            VocabItem(u'Wasser in stehenden Gewässern', _(u'Wasser in stehenden Gewässern')),
            VocabItem(u'Schwebstoffe in stehenden Gewässern', _(u'Schwebstoffe in stehenden Gewässern')),
            VocabItem(u'Sedimente in stehenden Gewässern', _(u'Sedimente in stehenden Gewässern')),
            VocabItem(u'Meer', _(u'Meer')),
            VocabItem(u'Meerwasser', _(u'Meerwasser')),
            VocabItem(u'Schwebstoffe im Meerwasser', _(u'Schwebstoffe im Meerwasser')),
            VocabItem(u'Sedimente im Meerwasser', _(u'Sedimente im Meerwasser')),
            VocabItem(u'Grundwasser', _(u'Grundwasser')),
            VocabItem(u'Grundwasser (nicht zur Trinkwassergewinnung)',
                      _(u'Grundwasser (nicht zur Trinkwassergewinnung)')),
            VocabItem(u'Rohwasser zur Trinkwassergewinnung', _(u'Rohwasser zur Trinkwassergewinnung')),
            VocabItem(u'Rohwasser, geschützt, aus Grund- und Tiefenwasser',
                      _(u'Rohwasser, geschützt, aus Grund- und Tiefenwasser')),
            VocabItem(u'Rohwasser, ungeschützt, aus Oberflächenwasser',
                      _(u'Rohwasser, ungeschützt, aus Oberflächenwasser')),
            VocabItem(u'Zisternenwasser', _(u'Zisternenwasser')),
            VocabItem(u'Sonstige Wässer', _(u'Sonstige Wässer')),
            VocabItem(u'Wasser zur Viehtränke', _(u'Wasser zur Viehtränke')),
            VocabItem(u'Bio-Indikatoren, Tabak und Arzneimittel', _(u'Bio-Indikatoren, Tabak und Arzneimittel')),
            VocabItem(u'Pflanzliche Indikatoren', _(u'Pflanzliche Indikatoren')),
            VocabItem(u'Blätter', _(u'Blätter')),
            VocabItem(u'Nadeln', _(u'Nadeln')),
            VocabItem(u'Gras', _(u'Gras')),
            VocabItem(u'Moose, Farne, Flechten u. Heidekraut', _(u'Moose, Farne, Flechten u. Heidekraut')),
            VocabItem(u'Wasserpflanzen', _(u'Wasserpflanzen')),
            VocabItem(u'Gras (REI)', _(u'Gras (REI)')),
            VocabItem(u'Tabak', _(u'Tabak')),
            VocabItem(u'Tabakblätter', _(u'Tabakblätter')),
            VocabItem(u'Zigaretten, Zigarren', _(u'Zigaretten, Zigarren')),
            VocabItem(u'Arzneimittel', _(u'Arzneimittel')),
            VocabItem(u'Ausgangsstoffe für Arzneimittel', _(u'Ausgangsstoffe für Arzneimittel')),
            VocabItem(u'Arzneimittelprodukte', _(u'Arzneimittelprodukte')),
            VocabItem(u'Luft und Niederschlag', _(u'Luft und Niederschlag')),
            VocabItem(u'Luft/Gammastrahlung', _(u'Luft/Gammastrahlung')),
            VocabItem(u'Gamma-Ortsdosis', _(u'Gamma-Ortsdosis')),
            VocabItem(u'Gamma-Ortsdosisleistung', _(u'Gamma-Ortsdosisleistung')),
            VocabItem(u'Luft/Neutronenstrahlung', _(u'Luft/Neutronenstrahlung')),
            VocabItem(u'Neutronen-Ortsdosis', _(u'Neutronen-Ortsdosis')),
            VocabItem(u'Neutronen-Ortsdosisleistung', _(u'Neutronen-Ortsdosisleistung')),
            VocabItem(u'Luft/Aerosole', _(u'Luft/Aerosole')),
            VocabItem(u'Aerosole', _(u'Aerosole')),
            VocabItem(u'Bilanzierungsmessung Aerosole', _(u'Bilanzierungsmessung Aerosole')),
            VocabItem(u'Luft/gasförmige Komponenten (einschl. Iod)', _(u'Luft/gasförmige Komponenten (einschl. Iod)')),
            VocabItem(u'Luft/gasförmiges Iod', _(u'Luft/gasförmiges Iod')),
            VocabItem(u'Luft/Edelgase', _(u'Luft/Edelgase')),
            VocabItem(u'andere gasförmige Komponenten (außer Iod u. Edelgase)',
                      _(u'andere gasförmige Komponenten (außer Iod u. Edelgase)')),
            VocabItem(u'Bilanzierungsmessung Luft/Iod', _(u'Bilanzierungsmessung Luft/Iod')),
            VocabItem(u'Bilanzierungsmessung Luft/Edelgase', _(u'Bilanzierungsmessung Luft/Edelgase')),
            VocabItem(u'Bilanzierungsmessung andere gasförmige Komponenten (außer Iod und Edelgase)',
                      _(u'Bilanzierungsmessung andere gasförmige Komponenten (außer Iod und Edelgase)')),
            VocabItem(u'Niederschlag', _(u'Niederschlag')),
            VocabItem(u'Niederschlag (Aktivitätskonzentration)', _(u'Niederschlag (Aktivitätskonzentration)')),
            VocabItem(u'nasse Niederschläge (Deposition)', _(u'nasse Niederschläge (Deposition)')),
            VocabItem(u'trockene Niederschläge (Deposition)', _(u'trockene Niederschläge (Deposition)')),
            VocabItem(u'Niederschlagsmenge', _(u'Niederschlagsmenge')),
            VocabItem(u'Spurenmessung Luft', _(u'Spurenmessung Luft')),
            VocabItem(u'Spurenmessung Luft - Aerosole', _(u'Spurenmessung Luft - Aerosole')),
            VocabItem(u'Spurenmessung Luft - gasförmige Komponenten (einschl. Iod)',
                      _(u'Spurenmessung Luft - gasförmige Komponenten (einschl. Iod)')),
            VocabItem(u'Spurenmessung Luft - Edelgase', _(u'Spurenmessung Luft - Edelgase')),
            VocabItem(u'Meteo-Umweltbereich', _(u'Meteo-Umweltbereich')),
            VocabItem(u'Nahrungsmittel (einschl. Trinkwasser)', _(u'Nahrungsmittel (einschl. Trinkwasser)')),
            VocabItem(u'Milch', _(u'Milch')),
            VocabItem(u'Sammelmilch (Kuh-)', _(u'Sammelmilch (Kuh-)')),
            VocabItem(u'Hofmilch (Kuh-)', _(u'Hofmilch (Kuh-)')),
            VocabItem(u'bearbeitete Trinkmilch (Kuh-)', _(u'bearbeitete Trinkmilch (Kuh-)')),
            VocabItem(u'Milch anderer Tiere (Schaf, Ziege, Stute)', _(u'Milch anderer Tiere (Schaf, Ziege, Stute)')),
            VocabItem(u'Humanmilch', _(u'Humanmilch')),
            VocabItem(u'Frischgemüse (einschl. Kartoffeln und Pilze)',
                      _(u'Frischgemüse (einschl. Kartoffeln und Pilze)')),
            VocabItem(u'Blattgemüse, ungeschützter Anbau', _(u'Blattgemüse, ungeschützter Anbau')),
            VocabItem(u'Wurzelgemüse, ungeschützter Anbau', _(u'Wurzelgemüse, ungeschützter Anbau')),
            VocabItem(u'Fruchtgemüse, ungeschützter Anbau', _(u'Fruchtgemüse, ungeschützter Anbau')),
            VocabItem(u'Sprossgemüse, ungeschützter Anbau', _(u'Sprossgemüse, ungeschützter Anbau')),
            VocabItem(u'Kartoffeln', _(u'Kartoffeln')),
            VocabItem(u'Blattgemüse, geschützter Anbau', _(u'Blattgemüse, geschützter Anbau')),
            VocabItem(u'Wurzelgemüse, geschützter Anbau', _(u'Wurzelgemüse, geschützter Anbau')),
            VocabItem(u'Fruchtgemüse, geschützter Anbau', _(u'Fruchtgemüse, geschützter Anbau')),
            VocabItem(u'Sprossgemüse, geschützter Anbau', _(u'Sprossgemüse, geschützter Anbau')),
            VocabItem(u'Wildpilze', _(u'Wildpilze')),
            VocabItem(u'Kulturpilze', _(u'Kulturpilze')),
            VocabItem(u'Sonstige Wildpilze', _(u'Sonstige Wildpilze')),
            VocabItem(u'Sonstiges Gemüse, ungeschützter Anbau', _(u'Sonstiges Gemüse, ungeschützter Anbau')),
            VocabItem(u'Sonstiges Gemüse, geschützter Anbau', _(u'Sonstiges Gemüse, geschützter Anbau')),
            VocabItem(u'Getreide', _(u'Getreide')),
            VocabItem(u'Getreidekörner (Weizen-,Roggen-, Gersten-, Hafer-, Mais-, Triticalenkörner)',
                      _(u'Getreidekörner (Weizen-,Roggen-, Gersten-, Hafer-, Mais-, Triticalenkörner)')),
            VocabItem(u'Sonstige Getreidearten', _(u'Sonstige Getreidearten')),
            VocabItem(u'Obst', _(u'Obst')),
            VocabItem(u'Schalenobst (Nüsse)', _(u'Schalenobst (Nüsse)')),
            VocabItem(u'Kernobst', _(u'Kernobst')),
            VocabItem(u'Steinobst', _(u'Steinobst')),
            VocabItem(u'Beerenobst, ungeschützter Anbau (außer Wald-/Wildbeeren)',
                      _(u'Beerenobst, ungeschützter Anbau (außer Wald-/Wildbeeren)')),
            VocabItem(u'Beerenobst, geschützter Anbau', _(u'Beerenobst, geschützter Anbau')),
            VocabItem(u'Wald-/Wildbeeren', _(u'Wald-/Wildbeeren')),
            VocabItem(u'Sonstige Obstarten', _(u'Sonstige Obstarten')),
            VocabItem(u'Fleisch', _(u'Fleisch')),
            VocabItem(u'Rindfleisch', _(u'Rindfleisch')),
            VocabItem(u'Kalbfleisch', _(u'Kalbfleisch')),
            VocabItem(u'Schweinefleisch', _(u'Schweinefleisch')),
            VocabItem(u'Geflügelfleisch', _(u'Geflügelfleisch')),
            VocabItem(u'Lammfleisch', _(u'Lammfleisch')),
            VocabItem(u'Haarwildfleisch', _(u'Haarwildfleisch')),
            VocabItem(u'Sonstiges Fleisch', _(u'Sonstiges Fleisch')),
            VocabItem(u'Fisch und Meeresfrüchte', _(u'Fisch und Meeresfrüchte')),
            VocabItem(u'Süßwasserfisch', _(u'Süßwasserfisch')),
            VocabItem(u'Seefisch', _(u'Seefisch')),
            VocabItem(u'Meeresfrüchte', _(u'Meeresfrüchte')),
            VocabItem(u'Fischerzeugnisse', _(u'Fischerzeugnisse')),
            VocabItem(u'Wasserpflanzen, Trockenprodukte', _(u'Wasserpflanzen, Trockenprodukte')),
            VocabItem(u'Trinkwasser', _(u'Trinkwasser')),
            VocabItem(u'Reinwasser aus geschützten Rohwasservorkommen',
                      _(u'Reinwasser aus geschützten Rohwasservorkommen')),
            VocabItem(u'Reinwasser aus ungeschützten Rohwasservorkommen',
                      _(u'Reinwasser aus ungeschützten Rohwasservorkommen')),
            VocabItem(u'Reinwasser aus Mischrohwasser', _(u'Reinwasser aus Mischrohwasser')),
            VocabItem(u'Rohwasser, geschützt, aus Grund- und Tiefenwasser (ungültig)',
                      _(u'Rohwasser, geschützt, aus Grund- und Tiefenwasser (ungültig)')),
            VocabItem(u'Rohwasser, ungeschützt, aus Oberflächenwasser (ungültig)',
                      _(u'Rohwasser, ungeschützt, aus Oberflächenwasser (ungültig)')),
            VocabItem(u'Zisternenwasser (ungültig)', _(u'Zisternenwasser (ungültig)')),
            VocabItem(u'Gesamtnahrung, Fertiggerichte und Getränke', _(u'Gesamtnahrung, Fertiggerichte und Getränke')),
            VocabItem(u'Gesamtnahrung', _(u'Gesamtnahrung')),
            VocabItem(u'Säuglings- und Kleinkindernahrung', _(u'Säuglings- und Kleinkindernahrung')),
            VocabItem(u'Fertiggerichte, verzehrsfertig (einschl. Suppen)',
                      _(u'Fertiggerichte, verzehrsfertig (einschl. Suppen)')),
            VocabItem(u'Fertiggerichte, Trockensubstanz (einschl. Suppen)',
                      _(u'Fertiggerichte, Trockensubstanz (einschl. Suppen)')),
            VocabItem(u'Getränke, trinkfertig, nicht alkoholisch (einschl. Tee und Kaffee)',
                      _(u'Getränke, trinkfertig, nicht alkoholisch (einschl. Tee und Kaffee)')),
            VocabItem(u'Getränke, Trockensubstanz, nicht alkoholisch (einschl. Tee und Kaffee)',
                      _(u'Getränke, Trockensubstanz, nicht alkoholisch (einschl. Tee und Kaffee)')),
            VocabItem(u'Getränke, alkoholisch', _(u'Getränke, alkoholisch')),
            VocabItem(u'Nahrungsmittelprodukte', _(u'Nahrungsmittelprodukte')),
            VocabItem(u'Käse aus Kuhmilch', _(u'Käse aus Kuhmilch')),
            VocabItem(u'Käse aus Milch anderer Tiere', _(u'Käse aus Milch anderer Tiere')),
            VocabItem(u'Milchprodukte außer Käse, Frischprodukte', _(u'Milchprodukte außer Käse, Frischprodukte')),
            VocabItem(u'Milchprodukte außer Käse, Trockenprodukte', _(u'Milchprodukte außer Käse, Trockenprodukte')),
            VocabItem(u'Milchprodukte außer Käse, haltbar gemacht', _(u'Milchprodukte außer Käse, haltbar gemacht')),
            VocabItem(u'Gemüseprodukte einschl. Kartoffeln, Frischprodukte auch tiefgefroren',
                      _(u'Gemüseprodukte einschl. Kartoffeln, Frischprodukte auch tiefgefroren')),
            VocabItem(u'Gemüseprodukte einschl. Kartoffeln, Trockenprodukte',
                      _(u'Gemüseprodukte einschl. Kartoffeln, Trockenprodukte')),
            VocabItem(u'Gemüseprodukte einschl. Kartoffeln, haltbar gemacht',
                      _(u'Gemüseprodukte einschl. Kartoffeln, haltbar gemacht')),
            VocabItem(u'Wildpilzprodukte, Frischprodukte auch tiefgefroren',
                      _(u'Wildpilzprodukte, Frischprodukte auch tiefgefroren')),
            VocabItem(u'Wildpilzprodukte, Trockenprodukte', _(u'Wildpilzprodukte, Trockenprodukte')),
            VocabItem(u'Wildpilzprodukte, haltbar gemacht', _(u'Wildpilzprodukte, haltbar gemacht')),
            VocabItem(u'Kulturpilzprodukte, Frischprodukte auch tiefgefroren',
                      _(u'Kulturpilzprodukte, Frischprodukte auch tiefgefroren')),
            VocabItem(u'Kulturpilzprodukte, Trockenprodukte', _(u'Kulturpilzprodukte, Trockenprodukte')),
            VocabItem(u'Kulturpilzprodukte, haltbar gemacht', _(u'Kulturpilzprodukte, haltbar gemacht')),
            VocabItem(u'Getreideprodukte außer Brot', _(u'Getreideprodukte außer Brot')),
            VocabItem(u'Brote und Gebäcke', _(u'Brote und Gebäcke')),
            VocabItem(u'Obstprodukte, Frischprodukte auch tiefgefroren',
                      _(u'Obstprodukte, Frischprodukte auch tiefgefroren')),
            VocabItem(u'Obstprodukte, Trockenprodukte', _(u'Obstprodukte, Trockenprodukte')),
            VocabItem(u'Obstprodukte, haltbar gemacht', _(u'Obstprodukte, haltbar gemacht')),
            VocabItem(u'Fleischprodukte u. Wurstwaren, ohne Wild, Frischprod. auch tiefgefr.',
                      _(u'Fleischprodukte u. Wurstwaren, ohne Wild, Frischprod. auch tiefgefr.')),
            VocabItem(u'Fleischprodukte u. Wurstwaren, ohne Wild, haltbar gemacht',
                      _(u'Fleischprodukte u. Wurstwaren, ohne Wild, haltbar gemacht')),
            VocabItem(u'Wildfleischprodukte u. -wurstwaren, Frischprod. auch tiefgefr.',
                      _(u'Wildfleischprodukte u. -wurstwaren, Frischprod. auch tiefgefr.')),
            VocabItem(u'Wildfleischprodukte u. -wurstwaren, haltbar gemacht',
                      _(u'Wildfleischprodukte u. -wurstwaren, haltbar gemacht')),
            VocabItem(u'Fischprodukte, Frischprod. auch tiefgefr.', _(u'Fischprodukte, Frischprod. auch tiefgefr.')),
            VocabItem(u'Fischprodukte, haltbar gemacht', _(u'Fischprodukte, haltbar gemacht')),
            VocabItem(u'Meeresfrüchteprodukte, Frischprod. auch tiefgefr.',
                      _(u'Meeresfrüchteprodukte, Frischprod. auch tiefgefr.')),
            VocabItem(u'Meeresfrüchteprodukte, haltbar gemacht', _(u'Meeresfrüchteprodukte, haltbar gemacht')),
            VocabItem(u'Sonstige Nahrungsmittel', _(u'Sonstige Nahrungsmittel')),
            VocabItem(u'Hühnereier', _(u'Hühnereier')),
            VocabItem(u'Honig', _(u'Honig')),
            VocabItem(u'weitere Nahrungsmittel', _(u'weitere Nahrungsmittel')),
            VocabItem(u'Umweltbereiche für Störfall', _(u'Umweltbereiche für Störfall')),
            VocabItem(u'Luft - Störfall', _(u'Luft - Störfall')),
            VocabItem(u'Luft/äußere Strahlung (Gamma-ODL) - Störfall',
                      _(u'Luft/äußere Strahlung (Gamma-ODL) - Störfall')),
            VocabItem(u'Luft/Aerosole - Störfall', _(u'Luft/Aerosole - Störfall')),
            VocabItem(u'Luft/gasförmiges Iod - Störfall', _(u'Luft/gasförmiges Iod - Störfall')),
            VocabItem(u'Luft/äußere Strahlung (Gamma-OD) -Störfall', _(u'Luft/äußere Strahlung (Gamma-OD) -Störfall')),
            VocabItem(u'Boden/-Oberfläche - Störfall', _(u'Boden/-Oberfläche - Störfall')),
            VocabItem(u'Bodenoberfläche (unversiegelt, in-situ, flächenbezogene Aktivität) - Störfall',
                      _(u'Bodenoberfläche (unversiegelt, in-situ, flächenbezogene Aktivität) - Störfall')),
            VocabItem(u'Boden - Störfall', _(u'Boden - Störfall')),
            VocabItem(u'Bodenoberfläche (versiegelt, in-situ, flächenbezogene Aktivität) - Störfall',
                      _(u'Bodenoberfläche (versiegelt, in-situ, flächenbezogene Aktivität) - Störfall')),
            VocabItem(u'Pflanzen/Bewuchs - Störfall', _(u'Pflanzen/Bewuchs - Störfall')),
            VocabItem(u'Weide- und Wiesenbewuchs - Störfall', _(u'Weide- und Wiesenbewuchs - Störfall')),
            VocabItem(u'Grünfutterpflanzen (außer Weide- und Wiesenbewuchs) - Störfall',
                      _(u'Grünfutterpflanzen (außer Weide- und Wiesenbewuchs) - Störfall')),
            VocabItem(u'Oberirdische Gewässer - Störfall', _(u'Oberirdische Gewässer - Störfall')),
            VocabItem(u'Oberflächenwasser (Fließgewässer) - Störfall',
                      _(u'Oberflächenwasser (Fließgewässer) - Störfall')),
            VocabItem(u'Oberflächenwasser (stehende Gewässer) - Störfall',
                      _(u'Oberflächenwasser (stehende Gewässer) - Störfall')),
            VocabItem(u'Oberflächenwasser (Viehtränke) - Störfall', _(u'Oberflächenwasser (Viehtränke) - Störfall')),
            VocabItem(u'Rindfleisch - Störfall', _(u'Rindfleisch - Störfall')),
            VocabItem(u'Kalbfleisch - Störfall', _(u'Kalbfleisch - Störfall')),
            VocabItem(u'Schweinefleisch - Störfall', _(u'Schweinefleisch - Störfall')),
            VocabItem(u'Geflügelfleisch - Störfall', _(u'Geflügelfleisch - Störfall')),
            VocabItem(u'Lammfleisch - Störfall', _(u'Lammfleisch - Störfall')),
            VocabItem(u'Blattgemüse, ungeschützter Anbau - Störfall',
                      _(u'Blattgemüse, ungeschützter Anbau - Störfall')),
            VocabItem(u'Wurzelgemüse, ungeschützter Anbau - Störfall',
                      _(u'Wurzelgemüse, ungeschützter Anbau - Störfall')),
            VocabItem(u'Fruchtgemüse, ungeschützter Anbau - Störfall',
                      _(u'Fruchtgemüse, ungeschützter Anbau - Störfall')),
            VocabItem(u'Sprossgemüse, ungeschützter Anbau - Störfall',
                      _(u'Sprossgemüse, ungeschützter Anbau - Störfall')),
            VocabItem(u'Kartoffeln - Störfall', _(u'Kartoffeln - Störfall')),
            VocabItem(u'Getreidekörner (Weizen, Roggen, Gerste, Hafer, Mais, Triticale) - Störfall',
                      _(u'Getreidekörner (Weizen, Roggen, Gerste, Hafer, Mais, Triticale) - Störfall')),
            VocabItem(u'Schalenobst (Nüsse) - Störfall', _(u'Schalenobst (Nüsse) - Störfall')),
            VocabItem(u'Kernobst - Störfall', _(u'Kernobst - Störfall')),
            VocabItem(u'Steinobst - Störfall', _(u'Steinobst - Störfall')),
            VocabItem(u'Beerenobst (außer Wald-/Wildbeeren) - Störfall',
                      _(u'Beerenobst (außer Wald-/Wildbeeren) - Störfall')),
            VocabItem(u'Sonstige Obstarten - Störfall', _(u'Sonstige Obstarten - Störfall')),
            VocabItem(u'Sonstige Mediengruppen', _(u'Sonstige Mediengruppen')),
            VocabItem(u'Baustoffe', _(u'Baustoffe')),
            VocabItem(u'mineralische Ausgangsstoffe für Baustoffe', _(u'mineralische Ausgangsstoffe für Baustoffe')),
            VocabItem(u'verarbeitete mineralische Baustoffe', _(u'verarbeitete mineralische Baustoffe')),
            VocabItem(u'organische Ausgangsstoffe für Baustoffe', _(u'organische Ausgangsstoffe für Baustoffe')),
            VocabItem(u'verarbeitete organische Baustoffe', _(u'verarbeitete organische Baustoffe')),
            VocabItem(u'Bodenschätze', _(u'Bodenschätze')),
            VocabItem(u'Rohgas', _(u'Rohgas')),
            VocabItem(u'Reingas', _(u'Reingas')),
            VocabItem(u'Bedarfsgegenstände und Kosmetische Mittel', _(u'Bedarfsgegenstände und Kosmetische Mittel')),
            VocabItem(u'Bedarfsgegenstände mit Lebensmittelkontakt', _(u'Bedarfsgegenstände mit Lebensmittelkontakt')),
            VocabItem(u'Bedarfsgegenstände zur Verpackung von Tabakerz. und kosmet. Mitteln',
                      _(u'Bedarfsgegenstände zur Verpackung von Tabakerz. und kosmet. Mitteln')),
            VocabItem(u'Bedarfsgegenstände mit Körperkontakt/ Spielwaren/ Kleidung',
                      _(u'Bedarfsgegenstände mit Körperkontakt/ Spielwaren/ Kleidung')),
            VocabItem(u'Bedarfsgegenstände zur Reinigung und Pflege',
                      _(u'Bedarfsgegenstände zur Reinigung und Pflege')),
            VocabItem(u'Kosmetische Mittel und Stoffe zu deren Herstellung',
                      _(u'Kosmetische Mittel und Stoffe zu deren Herstellung')),

        ]

        # Fix context if you are using the vocabulary in DataGridField.
        # See https://github.com/collective/collective.z3cform.datagridfield/issues/31:  # NOQA: 501
        if not IDexterityContent.providedBy(context):
            req = getRequest()
            context = req.PARENTS[0]

        # create a list of SimpleTerm items:
        terms = []
        for item in items:
            terms.append(
                SimpleTerm(
                    value=item.token,
                    token=str(item.token),
                    title=item.value,
                )
            )
        # Create a SimpleVocabulary from the terms list and return it:
        return SimpleVocabulary(terms)


SampleTypeFactory = SampleTypes()
