---
version: "3.8"

services:
  dokpool-instance:
    profiles:
      - dokpool_review
    build:
      context: ../../../
      dockerfile: dokpool/Docker/stack/dokpool/Dockerfile
    depends_on:
      - dokpool-postgres
      - dokpool-transfer
    deploy:
      mode: replicated
      replicas: 8
    environment:
      - DB_HOST=dokpool-postgres
      - DB_PORT=5432
      - DB_NAME=plone
      - DB_USER=plone
      - DB_PASS=plone
      - TRANSFER_DB_HOST=dokpool-transfer
      - TRANSFER_DB_PORT=5432
      - TRANSFER_DB_NAME=plone
      - TRANSFER_DB_USER=plone
      - TRANSFER_DB_PASS=plone
      - DOKPOOL_INSTANCE_PORT=9091
    networks:
      - dokpool_backend

  # Only for development & test
  # On production, we use the central patroni postgres
  dokpool-postgres:
    profiles:
      - dokpool_review
    image: postgres
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    ports:
      - "5432:5432"
    networks:
      - dokpool_backend

  dokpool-transfer:
    profiles:
      - dokpool_review
    image: postgres
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    ports:
      - "5433:5432"
    networks:
      - dokpool_backend


  dokpool-purger:
    profiles:
      - dokpool_review
    image: ghcr.io/kitconcept/cluster-purger:latest
    environment:
      PURGER_SERVICE_NAME: varnish
      PURGER_SERVICE_PORT: 8010
      PURGER_MODE: "compose"
      PURGER_PUBLIC_SITES: "['plone.localhost']"

  dokpool-varnish:
    profiles:
      - dokpool_review  
    build:
      context: dokpool-varnish
    environment:
      - VARNISH_BACKEND_HOST=stack_dokpool-instance
      - VARNISH_BACKEND_PORT=9091
      - VARNISH_HTTP_PORT=8100
      - VARNISH_BACKEND_COUNT=8
    ports:
      - 8100:8100
    networks:
      - dokpool_backend

networks:
  dokpool_backend:
